### ISSUE TITLE
Food too easy to get early game?

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#10]
"And... slow down on the food resources! I havent even lost all my saturation and I already have 32 sandwichs and 16 fried chicken! Without hunger overhaul.... that is a LOT of food"

Not sure how exactly to fix this, probably a case of trial and error until a balance is found

**Comment by AKTheKnight** [comment]
On a survey of the beta group:
"yes"
"The oranges can be used to make an orange sapling and then that + bone meal + juicer = food for days"

**Comment by johnnymobbins** [comment]
Snow and I will discuss this

**Comment by Nagapito** [comment]
The problem might not be the amount of food but instead the hunger/saturation levels they provide.
A pack of french fries gives me like 6 chunks of hunger and 8 or 9 saturation and I received 16 at the beginning. Still have 8 after what... 20-30 hours of gameplay?

So, if hunger/saturation is reduced, the food usage will increase and make more sense. Also... currently, who needs a big reactor if a piece of juice gives me 30K RF? A sandwichgives something like 100k... Build a couple of good generators and power is not a problem anymore

**Comment by johnnymobbins** [comment]
I have removed many of the food based rewards

**Comment by johnnymobbins** [comment]
@Nagapito Can you clarify how you are getting those power outputs? Are you talking about the Culinary Generator? Orange juice only gives me 20RF/t not 30k?

**Comment by AKTheKnight** [comment]
Any news on this? Another person has queried it on forum
