### ISSUE TITLE
Tinker Construct

### ISSUE THREAD

**Issue by Vash505** [SnowShock35/Obscurity#108]
When updating tool pieces it says THIS TOOL HAS INCORRECT DATA place this tool in a crafting window to update it. When new parts being replaced it knocks it down to the mining level previous along with changed with other parts. Such as the tool rod it knocks down the mining level with no experience update. It actually takes away the upgrade with any part exchange.

**Comment by SnowShock35** [comment]
Yeah sorry about this, will try and fix if we can but, not sure it's possible

**Comment by tibblaye** [comment]
did you spawn the pick in though nei? because if you did maybe making a custom pickaxe would help

**Comment by SnowShock35** [comment]
It's because I altered iguana tinker tweaks cfg. However, I'm reverting those changes for 1.1.14 so if u didn't use 1.1.13 you'll be fine

**Comment by Vash505** [comment]
The pick I was using was through the quest book. The wooden one that you
start off with.

**Comment by SnowShock35** [comment]
Somewhat fixed
