### ISSUE TITLE
[BUG] Desperate Times - Zombie Flesh turns into Leather

### ISSUE THREAD

**Issue by Kezarious** [SnowShock35/Obscurity#113]
As it says, Rotten flesh dropped by zombies turns into leather when placed on a drying rack, so the Desperate Times quest is uncompletable, unless there's some other way of getting Monster Jerky in the early game.

**Comment by SnowShock35** [comment]
@Kezarious Your leaving it on their too long it goes from one to the other

**Comment by Kezarious** [comment]
Oh... I didn't watch it, so I never realised. Is it mentioned in the quest book? Anway, thanks!

**Comment by johnnymobbins** [comment]
"The longer you leave it the tougher it gets"
