### ISSUE TITLE
"Look out trees!" sentence issue?

### ISSUE THREAD

**Issue by Insufficient-Charge** [SnowShock35/Obscurity#116]
The book says "You can tweak the cart to use the solar engine over the coal engine"

No solar engine is listed?

Sorry if this seems stupid, but you guys said even to post the smallest of issues . . . so I did :)

**Comment by AKTheKnight** [comment]
Thanks for reporting this. #BlameSnow?

**Comment by SnowShock35** [comment]
No #blameJohnny

**Comment by johnnymobbins** [comment]
Fixed for 1.1.15
