### ISSUE TITLE
Crafting teleportation rails

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#117]
"in the branch of industrial evolution, the job crafting teleportation rails. Crafted they are in the device Soul Binder. And the book does not take this quest, because I'm not Kraft them in the crafting table."

Crafting detection isn't working as they don't use vanilla crafting

**Comment by SnowShock35** [comment]
@johnnymobbins Change this quest to a detection Johnny; do for 1.1.15

**Comment by johnnymobbins** [comment]
Fixed for 1.1.15
