### ISSUE TITLE
Enderium recipe bypass

### ISSUE THREAD

**Issue by Insufficient-Charge** [SnowShock35/Obscurity#118]
When crafting enderium, using enderium blend, you can just melt the "enderium blend" in a smeltery instead of using an induction smelter.

This bypasses the use of pyrotheum dust in the recipe for enderium ingots.

**Comment by SnowShock35** [comment]
@Insufficient-Charge Pretty sure you require blazing pyrotheum to melt the enderium though, don't you?

**Comment by Insufficient-Charge** [comment]
I can put the blend in the smeltery and pour it into an ingot cast.

**Comment by SnowShock35** [comment]
Hmm okay. think this is a mod bug but I could try fix it maybe. it's not a huge deal though tbh :/

**Comment by Insufficient-Charge** [comment]
I know its a dumb issue but I noticed it so XD

thanks anyways.

**Comment by LyraelRayne** [comment]
This also works with the Thermal Smeltery (i.e. you can melt the enderium blend in a magma crucible and pour it into the ingot cast).

**Comment by SnowShock35** [comment]
Right this is fixed for the next version, now stop your whining :stuck_out_tongue:

**Comment by LyraelRayne** [comment]
I'll stop whining when Blizzes spawn in the Nether!

**Comment by SnowShock35** [comment]
So never then? :stuck_out_tongue_winking_eye:

**Comment by SnowShock35** [comment]
Fixed in 1.1.15_Beta
