### ISSUE TITLE
Can't open quest book?

### ISSUE THREAD

**Issue by thegameplayingcouple** [SnowShock35/Obscurity#120]
I don't know if this IS a pack issue or not, but a friend can't open his quest book.

**Comment by johnnymobbins** [comment]
Just saw this on stream. It was on a server.

**Comment by thegameplayingcouple** [comment]
Figured it out, you can close this, person had updated to .14, server still on .13

**Comment by AKTheKnight** [comment]
This will usually not be an issue (When a mod is updated they won't be able to join)
