### ISSUE TITLE
Progressive Automation needs updating

### ISSUE THREAD

**Issue by IainVM** [SnowShock35/Obscurity#121]
PA needs updating since the recommended pack 1.1.14 has the version PA of 1.6.19 which has this problem: https://github.com/Vanhal/ProgressiveAutomation/issues/156
Causing all PA machines to just spew items out instead of putting them in chests. Which has been fixed in the updated version.

**Comment by AKTheKnight** [comment]
Thanks for confirming that this is a known issue. I have alerted Snow

**Comment by Insufficient-Charge** [comment]
Now I know why my tree farm isn't working . . . :)

**Comment by SnowShock35** [comment]
Fixed in 1.1.15_Beta
