### ISSUE TITLE
Cube Moving quest doesn't require the player to actually complete the task

### ISSUE THREAD

**Issue by LyraelRayne** [SnowShock35/Obscurity#125]
Presumably the intention for the "Cube moving" quest is that the diamond provided by "Get to the cube" is used to move the cube. But because the quest will detect ANY compact machine of that size rather than an upgraded one the player can ultimately keep the diamond and use it for something else, like upgrading an early game tool. 

Requiring that the compact machine be upgraded for quest completion would remove this presumably unintended way of getting a free diamond. It'd also ensure that players understand what the deal is with upgrading (I personally didn't until much later in the game where I saw "upgraded" and had to look up what it meant).

**Comment by johnnymobbins** [comment]
This is a tricky one to detect correctly. Do t this k there is too much I can do.

**Comment by LyraelRayne** [comment]
1. Open the game with the quest editor enabled. 
1. Go to the cube, upgrade it and then pick it up with a pickaxe. 
1. Edit the quest item using the quest book to be precise detection and select the cube you have in your inventory.
1. Save

Should only detect machines which are set to the correct machine number. As long as that number doesn't change it should be fine.

It does mean that if the player breaks the cube without upgrading that they'll be stuck. But as it's a very early game quest perhaps that isn't the worst thing in the world.

**Comment by SnowShock35** [comment]
Yeah @LyraelRayne suggestion should work @johnnymobbins try it for 1.1.16 ;)

**Comment by johnnymobbins** [comment]
Fixed
