### ISSUE TITLE
Slime Fletching not craftable

### ISSUE THREAD

**Issue by dfranganillo** [SnowShock35/Obscurity#129]
"Forge the Darkness" quest "Custom Piercings" asks for 4 slime fletchings that are currently uncraftable either with blue slimes (or blocks) or green slimes (or blocks).

http://i.imgur.com/ZPCQL25.png

**Comment by McMorgenmantel** [comment]
That's actually not a bug. You have to smelt the blocks in order to gain slime crystals. These are the materials to use for the Tools Parts.

**Comment by SnowShock35** [comment]
You need to make the slime into slime crystals, look it up in NEI ;)
