### ISSUE TITLE
Smeltery

### ISSUE THREAD

**Issue by KacpixPl** [SnowShock35/Obscurity#13]
If you use the smeltery to double yellorium you get 288mb, as usual, but to make it into an ingot you need 1000mb. Not sure if troll or not.

**Comment by SnowShock35** [comment]
Will fix for 1.1.9 by reverting AOBD to previous build or removing the BigReactors Integration

**Comment by SnowShock35** [comment]
Fixed in 1.1.9. Disabled the All Thaumcraft support and Removed the ability to process yellorium in Tinkers Construct smeltery
