### ISSUE TITLE
Oddity with sapplings %

### ISSUE THREAD

**Issue by dfranganillo** [SnowShock35/Obscurity#130]
I've had to cheat twice in order to continue with the pack. The reason are that:
 * The slime tree didn't throw any sapplings
 * The greatwood tree also, didn't throw any sappling.

The thing is, both happened inside a Cube, and my "overworld" tree farm works flawlessly.

**Comment by AKTheKnight** [comment]
That may be due to the percentages on the actual trees from their respective mods. I will chat to Snow about what we can do

**Comment by SnowShock35** [comment]
@dfranganillo Need more information please. Screenshots, version, steps to repeat ect ;)

**Comment by dfranganillo** [comment]
It happens in 1.14 too, screenshots...of what, I got no sappling, thats all.
It happened in the deep dark too, I planted a greatwood and no sappling.
Trees I have tried that expose this behaviour:
 - Slimy sappling
 - Greatwood sappling
 - Silverwood sappling

It seems to me that the % of getting a sappling in those trees is somehow lowered.

**Comment by SnowShock35** [comment]
@dfranganillo  Ik silverwoods and greatwoods have always been low and slimy are also kinda low but never expected the player to get < 1. As for what I can do, there isn't much. Might be able to tweak this not 100% yet. If not then I suggest just spawning one  in if u didn't get a sapling.

**Comment by LyraelRayne** [comment]
Pretty sure there's a chest hidden in the slime room which contains saplings.

You can get greatwood and silverwood saplings by completing "Thaumic Vision" quite early on in the "Thaumic Revolution" quest line.

I also found some Pechs floating around in a taint biome somewhere near my base who could possibly be traded with to get more saplings (is that still a thing?).

Considering the fact that no silverwoods appear naturally in the deep dark and losing the sapling can halt progress it might be worthwhile adding a recipe to trade silverwood leaves for saplings somehow. Or adding an expensive recipe to buy them at the market (where one may already buy all manner of sapling).

**Comment by LyraelRayne** [comment]
Oh, and I did some testing with my trusty lumber axe and fairly regularly got three silverwood saplings from a tree, although sometimes I got one and sometimes I got none. This works both inside and outside compact machines. 

One further note: Don't try to use the progressive automation chopper with Thaumcraft trees. https://github.com/Vanhal/ProgressiveAutomation/issues/163

**Comment by LyraelRayne** [comment]
Oh, a repeatable daily quest for saplings might also work to fix this.

**Comment by johnnymobbins** [comment]
I know the issue issue with the Slimy trees is due to the Fast Leaf decay mod. If you create a block update next to the leaves (or just break one) all will fall. This drops many saplings in my tests. If you break trunk then the leaves manually the chances of getting a sapling are far lower. I have made a note to update the text in the Slimy Quest to reflect this.

**Comment by johnnymobbins** [comment]
That's a good idea, I'll add that too.

**Comment by johnnymobbins** [comment]
If anyone has suggestions for sapling recipes, please add them here so Snow can look over them.

**Comment by LyraelRayne** [comment]
Are recipes for the arcane worktable or the infusion altar an option?

**Comment by johnnymobbins** [comment]
Absolutely

**Comment by LyraelRayne** [comment]
For slimy sapling.

![image](https://cloud.githubusercontent.com/assets/11632412/8892427/0e775fca-339a-11e5-8b05-089113196e35.png)

**Comment by johnnymobbins** [comment]
Love it Lyrael.

**Comment by LyraelRayne** [comment]
If you wanted to avoid breaking the progression (so that the player needs to have reached the slime cube before making saplings) you could replace one of them with the slimy grass, but that runs the risk of perhaps running out of that and still not being able to make more.

**Comment by LyraelRayne** [comment]
For the silverwood I was thinking a harder recipe (for people who don't have any silverwood at all)
![image](https://cloud.githubusercontent.com/assets/11632412/8892497/9bc8f2b4-339d-11e5-8ae5-5d2b59e94f9b.png)

And an easier one, for those who already have silverwood but don't have saplings. Requires a silverwood wand due to the amount of Vis.
![image](https://cloud.githubusercontent.com/assets/11632412/8892499/bfb727b8-339d-11e5-9352-349e64d1b4d7.png)


Similar recipe concept for greatwood, although perhaps less expensive.

**Comment by LyraelRayne** [comment]
Another idea I had is that new JSONAble items could be created which can be found in the relevant cubes. These items could be added as a non-consumable item to the recipes in order to prevent the recipes being used before reaching the cubes.

**Comment by SnowShock35** [comment]
Will look into some recipes for these. I don't want to give every item that's hard to get a recipe though. I do want some rarity to somethings ;)

**Comment by LyraelRayne** [comment]
Naturally. It's important that these stay rare or hard to get, but at the moment they're not rare, they're unique. Unless you can somehow get them to spawn in worldgen? Or maybe in those dungeons.

**Comment by SnowShock35** [comment]
I'll see what I can do ;)

**Comment by konekog** [comment]
Alternative, which I think is better. Alter the thermal foundation lexicon whitelist to include 'logWood'. This will allow all wood logs to be converted to either the greatwood, which i have never had an issue of getting saplings with, and the silverwood, which i never get saplings. This also prevents the problem of filling the deep dark with magical forest biomes(created by the pure nodes inside the silverwood trees) on multiplayer servers. For some reason vanilla woods although able to be converted from are not able to be converted to(bug for cofh to work on).

**Comment by konekog** [comment]
forager pechs do still trade saplings ... i found best percentage to for silverwood to be gold blocks and gold armor chests and pants ... boots and helmet seemed to be lower trade rate.... in any case not impossible just more work than intially intended.

**Comment by LyraelRayne** [comment]
The real problem with Pech Foragers is that they want to trade valuable stuff for goddamn headcrumbs. Any chance of getting those removed from the list of stuff you can get in a trade?

**Comment by konekog** [comment]
Well since pech's use the dungeon loot as part of the loot table for trades. You could remove headcrumbs from the dungeon loot table, which conveniently can be done in the headcrumbs config file. Doing so would mean you would have to behead the headcrumbs to get the heads but i don't think you have a problem with that idea. Looking at Thaumcraft code, I didn't see a quick way to remove it just from the pech's loot table.

**Comment by LucidCrux** [comment]
I just had to cheat in an oak sapling on .14 because I didn't get a single sapling from the 2 in the chest or the one early quest reward. It would be nice if there were a simple repeatable quest or recipe for the basic saplings. It may be rare, but it does happen.

**Comment by LyraelRayne** [comment]
Oak saplings may be purchased in the Pam's market.

**Comment by SnowShock35** [comment]
Right so for now just added slimy sapling. Will do others for next version.
