### ISSUE TITLE
Problem with "Top or Bottom?" Quest

### ISSUE THREAD

**Issue by Loxo321** [SnowShock35/Obscurity#131]
The Quest lacks a "Select Task" button, making it impossible for me to submit any blueberry muffins through the Quest Delivery System. Additionally, I can't manually submit the muffins either because there's not enough space overall in my inventory.

**Comment by Insufficient-Charge** [comment]
You can manually submit muffins amount at a time. Per say, I needed 10 items to be submitted, I can click the "manual submit" button when I only have 5 items. The quest will then say 5/10

**Comment by Insufficient-Charge** [comment]
Still, the select task thing may be an issue.

**Comment by SnowShock35** [comment]
I'll leave @johnnymobbins johnny to take a look at this for you tomorrow

**Comment by johnnymobbins** [comment]
Fixed for 1.1.15
