### ISSUE TITLE
Compact Machine crash

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#133]
"I disconnected inside a compactmachine on my own server.
When I connected back today, I could get outside the compactmachine fine, but whenever I tried to go back inside, it told me "Internal Server Error".
I tried deleting the pack, deleting the server and the CompactMachine folder, but nothing worked. Here's a log (don't know if it's the right one)."
~samuelsam55
[Log: https://www.dropbox.com/s/65kxumi57cldf78/fml-server-latest.txt?dl=0]
{File in my dropbox as too large for pastebin. It's safe don't worry ~AK}

**Comment by SnowShock35** [comment]
Tbh that log is so big it can't tell me much from what ik of reading crash reports. My advice is to completely reinstall server and client and delete existing world's.
