### ISSUE TITLE
crashed - out of memory

### ISSUE THREAD

**Issue by Turmfalke2** [SnowShock35/Obscurity#134]
hi,
I just had the modpack (v .14) crash because it run out of memory. I have the max set to 4GB in the ftb launcher. I could give it more ram, but I am not sure it is supposed to need that much and java is pretty terrible when given to much ram.

**Comment by AKTheKnight** [comment]
How long had you been running the pack for?

**Comment by Turmfalke2** [comment]
Not sure, but I think less than 2 hours.

**Comment by AKTheKnight** [comment]
That is odd then. How much ram do you have on your computer?

**Comment by Turmfalke2** [comment]
8GB

**Comment by AKTheKnight** [comment]
Could you possibly post your log?

**Comment by Turmfalke2** [comment]
I have since continued playing, it wasn't anything special. Just a normal java-vm crash with the out of memory message due to malloc failing.

**Comment by AKTheKnight** [comment]
Hmm. Not sure if there is anything we can do then. It is a fairly resource heavy pack. If it happens again please grab the log and we will have a look and see if it is something we can help with

**Comment by Turmfalke2** [comment]
Ok, it crashed again after play for a bit more than 1 hour. As an additonal information, I had no such issues with v.11(?) and just updated today.
From what I can tell it always happened when I enter/leave a complex machine.
Here is the crash log:
http://www.pastebin.ca/3070972
