### ISSUE TITLE
Automation is the game!

### ISSUE THREAD

**Issue by Turmfalke2** [SnowShock35/Obscurity#135]
hi,
I have the 3 machines and 4 upgrades, but I can't complete the quest. The button is just missing - it is not an issue with inventory space.

**Comment by AKTheKnight** [comment]
Can you please post a screenshot?

**Comment by Turmfalke2** [comment]
http://ibin.co/29PRCjxqE5qL
http://ibin.co/29PRQTh9WXhJ

**Comment by AKTheKnight** [comment]
You have completed the quest. It is just a crafting detection. Now just select one of the four rewrds to have at the bottom and press claim reward (should show up)

**Comment by Turmfalke2** [comment]
I can't select them

**Comment by AKTheKnight** [comment]
Hmm, that is very odd. Give me a bit to check this myself

**Comment by SnowShock35** [comment]
@Turmfalke2 Okay so from what @AKTheKnight tested the quest is fine in his version so it's most likely a bugged quest. Here is some instructions on how to fix it. Hope this helps -Snow https://github.com/SnowShock35/Obscurity/wiki/Fixing-Broken-Quests
