### ISSUE TITLE
Coconut trees punch holes through the compact machine walls

### ISSUE THREAD

**Issue by Turmfalke2** [SnowShock35/Obscurity#136]
hi,
Coconut trees from Pam's harvest craft punch holes through the walls from compact machines. I am pretty sure the walls are supposed to be indestructible.

**Comment by AKTheKnight** [comment]
Uhh yeah I think they are meant to be. However if you go outside of it you should find you get nausea and teleported back inside.

I believe it's the same as trees breaking through bedrock. They just replace stuff in their way

**Comment by SnowShock35** [comment]
When the tree grows it's not using the same code as the ones from vanilla in that it can replace any block. It should check for blocks in that area and their hardness level and depending on that it should bypass it or not.

**Comment by SnowShock35** [comment]
Okay so this has been apparently fixed in 1.7.10j of HarvestCraft, will update for next version ;)

**Comment by SnowShock35** [comment]
Updated Pam's HarvestCraft to 1.7.10j in 1.1.16. Therefore issue is now fixed.
