### ISSUE TITLE
Steve's Factory Manager

### ISSUE THREAD

**Issue by IngotCrafter** [SnowShock35/Obscurity#139]
When loading the pack, it says;

Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found
StevesFactoryManager : Any

**Comment by SnowShock35** [comment]
Hi @IngotCrafter ,

I'm going to need some more specifics on the issue

* Pack version
* Screenshot of the mods folder (If you know how to locate it)

If you could supply these it will help us to get to the bottom of your issue.
Thanks
-Snow
Lead Pack Developer & Project Manager

**Comment by SnowShock35** [comment]
@IngotCrafter If you could can you report some more information after reinstalling version 1.1.14 if it still doesn't load ;)

**Comment by SnowShock35** [comment]
No information for over a month. Being closed!
