### ISSUE TITLE
[1.1.15] Magma Crucible does not accept luminite

### ISSUE THREAD

**Issue by LyraelRayne** [SnowShock35/Obscurity#140]
In 1.1.15 the ability to melt luminite in the smeltery was added but it appears that the same functionality was not added to the magma crucible. 

Steps to reproduce:
1. Place magma crucible and power source.
2. Attempt to put luminite dust and/or ore into magma crucible.
3. #blamesnow

**Comment by SnowShock35** [comment]
Ore will never have processing for magma crucible.  However, will add luminite dust melting ;)

**Comment by SnowShock35** [comment]
Added dust. Not going to add ore because doesn't fit in IMO.
