### ISSUE TITLE
"Nether again" quest asks the player to "Pick one" but quest only offers one option from which to choose.

### ISSUE THREAD

**Issue by LyraelRayne** [SnowShock35/Obscurity#145]
![image](https://cloud.githubusercontent.com/assets/11632412/8874713/be19cfb6-3256-11e5-84f7-cc0c309a752f.png)

**Comment by LyraelRayne** [comment]
Singular quest has the same issue.

![image](https://cloud.githubusercontent.com/assets/11632412/8875842/276c3366-325f-11e5-9667-0f11cbab7768.png)

**Comment by AKTheKnight** [comment]
Well, pick one then :P You can't pick option 2

**Comment by LyraelRayne** [comment]
Well I never said it was a game breaking issue!

**Comment by LyraelRayne** [comment]
![image](https://cloud.githubusercontent.com/assets/11632412/8888994/7e6650d0-3308-11e5-93d5-b0d2fc0c6475.png)

**Comment by johnnymobbins** [comment]
Fixed
