### ISSUE TITLE
Ender dragon egg escapes into the void

### ISSUE THREAD

**Issue by LyraelRayne** [SnowShock35/Obscurity#146]
When attempting to mine the Ender Dragon egg from the compact machine the egg almost always teleports into the void (at least, I can't see anywhere else it would have gone), destroying the only egg in the world. 

Perhaps add another one to the chest, kind of like what is done with the slime saplings in slime world in case the only tree doesn't drop one.

**Comment by johnnymobbins** [comment]
I'm torn on this one. I was kind of happy to leave the egg for the people who k ow how to move it. People who don't miss out! I don't think it is really used for much.

**Comment by LyraelRayne** [comment]
It isn't, but it's a nice trophy. A compromise might be to teleport outside the cube and fill up the empty space around it (up to seven blocks vertically and fifteen blocks horizontally),with bedrock so that it has nowhere outside the cube to jump to. Then people can chase it around the cube without potentially losing it forever.

**Comment by johnnymobbins** [comment]
Or just hit it with a piston in the cube and collect it :P

**Comment by LyraelRayne** [comment]
That's no fun! Chase the egg!
