### ISSUE TITLE
New update won't load old worlds properly 

### ISSUE THREAD

**Issue by Bluebobdopepants** [SnowShock35/Obscurity#152]
I've played the obscurity pack for about 3 days now, but after the pack update (1.1.15) the old world I was using will no longer work, when I check the console, the last message is always "attempting to load JABBA data"  and won't move past that and the world will not load. Anything I can do to fix it?
![untitled](https://cloud.githubusercontent.com/assets/13512936/8896616/b4daf0d6-33b6-11e5-89cf-60690f5df7ef.png)

**Comment by SnowShock35** [comment]
1.7.1? That pack version doesn't even exsist
:/

**Comment by tornade59** [comment]
I have the same problem at the moment.
I tried to disable jabba but it has no effect, so the problem is from elsewhere :s

**Comment by Bluebobdopepants** [comment]
Ah, I was going off this 

![wqasdd](https://cloud.githubusercontent.com/assets/13512936/8896978/ea5d0e6a-33c0-11e5-8087-b8cc14420b7a.png)

The proper version would be 1.1.15 then

**Comment by medina102** [comment]
Same on waking up this morning my boyfriend warned me not to update as the world just won't load.

**Comment by LyraelRayne** [comment]
I have replicated this. Reverting the HQM config folder back to the 1.1.14 version seemed to fix it. 

The game appears to be stuck on HQM's readData() function. 

![image](https://cloud.githubusercontent.com/assets/11632412/8908088/5adf13a2-34bd-11e5-8336-bc582cd8bbad.png)

**Comment by Celadeus** [comment]
I tried it and it seems to work, thx bro

**Comment by johnnymobbins** [comment]
@Snowshock35 is this HQM related or because of the new map downloader?

**Comment by SnowShock35** [comment]
@johnnymobbins Nope! It's HQM related :/

**Comment by johnnymobbins** [comment]
Crap, any idea what's causing it?

**Comment by johnnymobbins** [comment]
Crap, any idea what's wrong with this version?

**Comment by SnowShock35** [comment]
@johnnymobbins No idea, you around in the morning to talk about this? (your evening)

**Comment by johnnymobbins** [comment]
Yeah mate. Let me know when you get up.

**Comment by SnowShock35** [comment]
K will do

**Comment by johnnymobbins** [comment]
It was a change to the 1st quest. Change has been reverted.
