### ISSUE TITLE
Inscribing Storage Quest Not Updating.

### ISSUE THREAD

**Issue by medina102** [SnowShock35/Obscurity#153]
I made an inscriber and then crafted all of the required processors but the quest is still sayin 0% for all processors. (Obscurity 1.1.14)

**Comment by LyraelRayne** [comment]
Appears to be a duplicate of https://github.com/SnowShock35/Obscurity/issues/142

**Comment by medina102** [comment]
Yes I did use the HQM edit to pass it. I was just doing my bit to help test the pack incase it hadn't been fixed, just had the same thing happen with the 4K storage devices I made but now i see Johnny is making all of them detection so I will hold off on any more problem reporting until i can get into 1.1.15 thanks :)
