### ISSUE TITLE
Jared's Map Downloader Dialogs behind Main Window

### ISSUE THREAD

**Issue by smisch** [SnowShock35/Obscurity#154]
Since 1.1.15 you are using Jared's Map Downloader which I believe produces two dialogs during startup asking the user whether they want to download certain files. These dialogs spawn behind the main window that shows the current loading progress. Loading stops until the user responds to these dialogs. The user might not see these dialogs and will therefore get the impression as if the loader froze. 

Steps to reproduce:
1. Launch 1.1.15 game. 
2. Loading gets stuck when dialogs appear. For me it was in post-initialization when loading Jared's Map Downloader.

System:
Windows 7 Professional N 64-bit
Java 1.8.0_31 64-bit

I updated from 1.1.14, removed the updated 1.1.15 and downloaded a fresh copy of 1.1.15. The issue was present in both cases.

**Comment by smisch** [comment]
I was unable to report this bug to the author of Jared's Map Downloader because there doesn't appear to be any official project site, nor any repository. 

If you are unable to resolve this issue, might I suggest using different mods like 

http://minecraft.curseforge.com/mc-mods/226447-resource-loader
http://minecraft.curseforge.com/mc-mods/222536-hardcore-map-reset

**Comment by jaredlll08** [comment]
Sorry, I am currently extremely sick, and have not been feeling well enough to fix this.
Also here is the repo:
https://github.com/jaredlll08/JMD

**Comment by smisch** [comment]
Thank you for the repository link jared. There is no need for apologies. You are providing a free service for the community after all. :-) Thank you for that. Get well soon.

**Comment by SnowShock35** [comment]
@smisch The reason I haven't used these mods (And I am using resource loader) is for multiple reasons
1. The file size goes up hugely with the resource pack which means slower update time.
2. Hardcore map reset is a stupid dumb mod. It requires you to have two saves of the world for the template copying to work correctly which IMO is stupid
3. Like jared says he's ill but, gonna try and get that issue fixed for 1.1.16 ;)

**Comment by smisch** [comment]
Thanks for the details on why you (didn't) chose these mods. I'm not a modpack dev myself. I just looked at what other modpacks used to get this job done. So please excuse my ignorance. :-)

I'm looking forward to 1.1.16. I really enjoyed your modpack so far.

**Comment by SnowShock35** [comment]
Removed Jared's Map Downloader in 1.1.16. Therefore, fixing this issue.
