### ISSUE TITLE
Jared's Map Downloader does not work on Linux

### ISSUE THREAD

**Issue by DeltaWhy** [SnowShock35/Obscurity#155]
It appears JMD uses hard-coded backslashes in paths, which causes it to not work on Linux (and probably Mac). Pack version 1.1.14 (without JMD) works fine, but version 1.1.15 will not let me create a world as the downloaded files are in the wrong place.

**Comment by SnowShock35** [comment]
Okay thanks for this. For now use 1.1.14 ;)

**Comment by jaredlll08** [comment]
Sorry about this, what is the linux slashes in paths?

**Comment by LyraelRayne** [comment]
You should be using File.separator as the path separator character rather than hard-coding it, but failing that using '/' will work on Windows, Linux and Mac whereas '\' only works on Windows.

**Comment by johnnymobbins** [comment]
Lyreal, are you a genius? You certainly seem like it!

**Comment by LyraelRayne** [comment]
Nah just a professional Java dev :P I've been writing Java for nearly 7 years now plus the bit I did at uni. I'd bloody well want to know this stuff!

**Comment by SnowShock35** [comment]
Removed Jared's Map Downloader in 1.1.16. Therefore, fixing this issue.
