### ISSUE TITLE
Cant craft Nether Gates in ME System.

### ISSUE THREAD

**Issue by johnnymobbins** [SnowShock35/Obscurity#156]
Crafting recipe comes up but cant click to collect.

**Comment by SnowShock35** [comment]
#blameMinetweaker as usual. Can't do anything about it. Maybe add a note in quest book @johnnymobbins

**Comment by johnnymobbins** [comment]
Seems to work fine now in 1.1.15?

**Comment by SnowShock35** [comment]
Huh weird okay will close it then
