### ISSUE TITLE
Ludicrite ingot on fluid transposer disabled

### ISSUE THREAD

**Issue by Celadeus** [SnowShock35/Obscurity#158]
When i tried to make some ludicrite ingot in the fluid transposer, with 4 enderium ingot and 4000mb of primal mana, nothing happened.
So i checked in the NEI recipe and i saw the one with fluid transposer hasn't any quantity of primal mana showed. So i was unable to process with fluid transposer.

I then tried to use the recipe with Tconstruct smeltery, but it is 10k mb of primal mana instead of 1k for 1 ingot ... is it intended or ... ?

Cause it's already kinda hard to make a ludicrite block, if it is now 10x more expensive :/

Edit : I'm in 1.1.15, with HQM config folder from 1.1.14

**Comment by SnowShock35** [comment]
Ah woops :stuck_out_tongue: Okay I'll have this fixed for 1.1.16. And @Celadeus your a smart man changing back to the old hqm version ;)

**Comment by SnowShock35** [comment]
Okay so it wasn't broken. It did require 10 buckets but the nei integration must have been broken or not allowed to show above 8 buckets. Reduced it to 4 for both smeltery and fluid transposer. Fixing Issue
