### ISSUE TITLE
Quest icons showing with no tasks?

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#16]
"After completing the smeltery quest, 4 quests show up with no tasks and icons for a dark iron pickaxe, dark iron armour, Tier 5 ender io jetpack and dark iron jetpack plating. 
I am assuming this quests are hidden trigger quests and should had stayed hidden, right?"

**Comment by SnowShock35** [comment]
Woops! Will be fixed in next version. My bad :p
