### ISSUE TITLE
Middle Click Sorting in Locker

### ISSUE THREAD

**Issue by arman258** [SnowShock35/Obscurity#160]
Where ever I try to middle sort clock in locker, the game crashes on me:
 Game Version: 1.1.14 on CurseVoice
Crash Report: http://pastebin.com/WuUAsHcJ

**Comment by Insufficient-Charge** [comment]
I have not been having the same problem, which is odd.

**Comment by SnowShock35** [comment]
@arman258 There is probably an item in there that doesn't like being sorted. Just try remove everything and put a few stacks of dirt cobble gravel then middle click. If it still doesn't work let us know.

**Comment by LyraelRayne** [comment]
Closing due to no response for 14 days and it's marked "can't fix". Will re-open if the reporter returns.
