### ISSUE TITLE
Bad Aim? quest issue

### ISSUE THREAD

**Issue by konekog** [SnowShock35/Obscurity#161]
I crafted 64 of the ender shot bullets at once and took them out of the crafting table all at once with shift click. The quest only gave credit for 8 of the 64. I believe, its an issue of only registering the first craft when using the shift click. This may be something that has to go back to HQM instead of here but there is already a similar issue opened at https://bitbucket.org/Newcastlegeek/hqm-bugtracker/issues/78/quests-with-multiple-outputs-on-craft-only. So I am giving this issue to you as well  to track it and in case its in the way the quest is constructed on your end.

**Comment by johnnymobbins** [comment]
Yeah that is a know issue, Cant really fix unless HQM updates.

**Comment by LyraelRayne** [comment]
@johnnymobbins you could change it to detection rather than crafting. Alternately, you could put a warning in the quest text that the crafts need to be done individually, but nobody would read it :P
