### ISSUE TITLE
Glowstone Problem?

### ISSUE THREAD

**Issue by zzzz14767** [SnowShock35/Obscurity#162]
I'm not sure if this was intentional or  not, but I figured I'd report it anyway. Since the vanilla recipe for glowstone was removed, the only way to get glowstone blocks is to cover glass with molten glowstone in the smeltery. But, nei says you need 10000 mb of it, or 40 glowstone dust for one block, which is ludicrous, condsidering you need 2 pyrotheum dust per dust. The other way is to trade with villagers, which is pretty cheap. Please change this either way, or please explain why it's so f*cking expensive!

**Comment by johnnymobbins** [comment]
I believe it will be changed back to just a 4 dust to one block ratio in the next version. 

Awaiting @SnowShock35 to confirm...

**Comment by SnowShock35** [comment]
Yes will change this for 1.1.16

**Comment by EfficiencyVI** [comment]
I actually liked that feature, it makes it more challenging. Using 4 glowstone just means that you have to keep your smeltery to the end game which I usually don't do so it would be cool if you could add a receipe to the fluid transposer too so that you can automate it without a large structure.

**Comment by LyraelRayne** [comment]
Assigning to snow as he said he'll fix it.

**Comment by SnowShock35** [comment]
Working on it ;)

**Comment by SnowShock35** [comment]
Recipes for glowstone are in. They are slightly more expensive to make it in crafting and half the price in materials if u use fluid transposer or smeltery.
