### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by Insufficient-Charge** [SnowShock35/Obscurity#164]
The loading screen is locked at "Jared's map downloader" and I've been waiting very long for it to load. Several hours.

Before, in 1.1.14, it only took a couple minutes before it loads. It now has been taking longer than three hours.

Help :(

**Comment by Insufficient-Charge** [comment]
Saw another one of these issue and missed it already being posted. Sorry 'bout the extra issue :)

**Comment by furleoxnop** [comment]
Which issue was it listed under?
