### ISSUE TITLE
Change AE recipies to Luminite instead of Glowstone

### ISSUE THREAD

**Issue by johnnymobbins** [SnowShock35/Obscurity#166]
Spatial Componant *Replace w/ Luminte
ME Storage Componant *Replace w/ Luminte
ME Illuminated Panel *Replace w/ Luminte
Paint Ball *Replace w/ Luminte
Blank Pattern *Replace w/ Luminte
Dense Cable *Replace w/ Luminte
Smart Cable *Replace w/ Luminte

**Comment by SnowShock35** [comment]
@VikeStep hey dude could you look into adding this to obscurity tweaks as ae2 uses a custom crafting handler minetweaker can't touch it.

**Comment by VikeStep** [comment]
I can have a look at it.

**Comment by VikeStep** [comment]
Have you looked into possibly using ModTweaker?
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Applied_Energistics_2_Support

**Comment by SnowShock35** [comment]
Okay so I've added one for blank patterns as they are a basic thing and they required 3. But in all honesty, AE2 isn't supposed to be easy and there are plenty of glowstone obtaining methods now in.
