### ISSUE TITLE
pumpkins arent growing on the stalk..

### ISSUE THREAD

**Issue by voigtstr** [SnowShock35/Obscurity#170]
the stalks mature fine with bonemeal.  have tried with both tilled and non tilled adjacent dirt blocks... so far have not been able to grow a single pumpkin.

**Comment by LyraelRayne** [comment]
Which version are you playing? I know I have definitely had pumpkins grow in my 1.1.14 world. Keep in mind that pumpkins and other crops do need a fairly high light level (I had to place regular torches pretty much on top of mine to make them grow outside of the cubes). Try planting some inside of a compact machine. The light level inside those is always high enough and the machines are always chunk loaded which should make sure that they grow.

**Comment by voigtstr** [comment]
I'm also using 1.1.14 and have used the first 3x3 compact machine to plant pumpkin seeds.

**Comment by Nila24** [comment]
Mine grow fine inside and outside of machines. Need light level 9 or more for the stalk. Pumpkins do need regular dirt (not sure about tiled) or grass for the grown pumpkin itself - can not be cobble and such in my experience. You can grow them (and anything else) in seconds with watering can.

**Comment by LyraelRayne** [comment]
That's really strange. Is the soil your pumpkin on hydrated?

**Comment by LyraelRayne** [comment]
Also are other crops growing for you?

**Comment by voigtstr** [comment]
Other crops would only grow with bonemeal, so I assume light levels are the issue. I'll start a new world again tonight, and this time try the interdiction torch (it seems brighter than normal torches), and also a farm in the first 3x3 cube. Are cubes bright enough to not require extra torches? Yes the water was hydrated (by a central trench with running water).  Does the F3 screen give light level?

**Comment by LyraelRayne** [comment]
The bl number on the F3 screen is apparently the light level. 

Cubes ought to be bright enough. I know I've grown pumpkins, melons, cotton and spice leaves inside of one. 

The interdiction torch does indeed produce enough light to have a small farm. I was growing wheat in my front window where I'd left the torch outside.

**Comment by zzzz14767** [comment]
I did some experimenting, and the walls of the cube give off the maximum light level, so everything will grow as long as you don't completely wall it in. Oh, and the RL value is the exact light level at the block your head is in.

**Comment by voigtstr** [comment]
Everything is fine now growing stuff in a 9x9 cube, cheers!
