### ISSUE TITLE
Too easy Charcoal->Coal Conversion

### ISSUE THREAD

**Issue by Nila24** [SnowShock35/Obscurity#172]
1 Charcoal->8 Fuel pellets-> 1 Coal. Pretty easy with simple SFM setup. 
The coal is supposedly much more valuable - it takes 2 coal dust for 1 steel instead of 4 charcoal dust, also coal can be used in QED to triple the ores, whereas charcoal can not. Charcoal literally grow on trees so it is extremely easy to have a ton of it early game. 
Probably can be easily solved by removing pellet->coal recipe.

**Comment by zzzz14767** [comment]
But coal is literally everywhere, considering you're in a mining dimension, so not really that op. Not to mention that the 128 dark steel balls you're given as a quest reward can be used in the SAG mill to get sh*t tons more materials from ores, especially if you use that silky gem you get as another quest reward.

**Comment by EfficiencyVI** [comment]
I would just change the receipe to either use 2 coal or 2 charcoal dust. If you have an Ender quarry running you will get regular coal much faster than you can burn wood. In this world it doesn't make too much sense to nerf charcoal.

**Comment by Nila24** [comment]
I tend to go automated charcoal->steam dynamos first thing, so I usually have much more charcoal than coal. 

As for which is faster for coal, weeeelll.... I have full farm station on (tall) jungle trees. On its own (no bonemeal and such) it produces around as many as 128 furnaces can constantly burn - It would probably take speed 3 ender quarry to match that on regular coal, but that is endgame stuff. 

It was at this point I wondered whether converting all that charcoal to coal (all it takes is a few comands in SFM)  would be considered cheating. You can also compress coal into blocks which burn for additional 10% bonus, which is significant. 
  
Using coal in QED to triple ores I do not consider cheating, since you basically can not automate that.  

By the way all that charcoal then goes to 64 of augmented steam dynamos (copper and silver are mostly useless anyway), but is nowhere near enough (like 30%) to sustain a rated 40KRF/t  of that setup... Might add few more farm stations and test how many furnaces can be fitted to normal compact machine (it is 81 for small machine ;-). 

Yea, I know, big reactors for power and stuff, but augmented dynamos are cool as well - especially when you stuff them in compact machine. By the way - aside from needing tons of coal, dynamos are more rf/block than BR...

**Comment by LyraelRayne** [comment]
How exactly are you doing this? I'm in 1.1.15 and I can't see any use for fuel pellets other than as fuel. Either it's been fixed in this version or I'm dumb :P

**Comment by SnowShock35** [comment]
This is already fixed in 1.1.15. 

Please **DO NOT** play this version though it's not recommended. Please wait for 1.1.16
