### ISSUE TITLE
Soul Fragment is useless

### ISSUE THREAD

**Issue by EfficiencyVI** [SnowShock35/Obscurity#174]
When you complete the quest "Cursed Rituals" you can decide to get a soul fragment. This soul fragment has the meta id 3 and can't be used for anything, it is a creative item. As far as I know it is intended to give you the health back if you give your reinforced watering can back but so far this is not implemented.

If it is intended to give the user a useful item it should be the 4503 soul fragment. BTW epic reward bags … my 5th conduit probe, 16 Carpenter's Blocks and 16 torches? Srly? It would be cool if that would be balanced better. And BTW 2 the tuberous flux capacitor is a "rare reward" … it is a lead nugget and a potatoe? I can craft a dozen of them 15 minutes after I started a new world. All other broken quests have already been reported as far as I know.

And please please please please please … if the mod pack relies so much on Thaumcraft in the mid game please add thaumic energistics to the pack (and AE Stuff please) because golems are kind of 2014 and throwing certus quartz in water is pretty annoying without Botania. :-D

**Comment by LyraelRayne** [comment]
Right clicking with the soul fragment gives you your 10% health back. It only works if you've lost 10% due to crafting a regular soul fragment. If you don't want/need that particular reward that's fair enough, but it isn't useless.

**Comment by LyraelRayne** [comment]
I've created separate issues for your other complaints as they are legitimate complaints in their own right and should be considered separately.

**Comment by EfficiencyVI** [comment]
Well, you cannot look this item up unless you know what to google for and the only thing I found was a tweet by RWTema. Maybe the other item would be more useful here as you can craft with it.

**Comment by LyraelRayne** [comment]
I'll leave it up to @SnowShock35  and @johnnymobbins to decide whether to change it. IMO it's fine but I can see the merit in what you're asking for as well.

**Comment by SnowShock35** [comment]
@EfficiencyVI This reward is actually extremely valuable. Rewards and reward bags are gonna get a redo for 1.2.X so it might be removed then. I honestly don't see the problem here. Therefore, closing this issue

**Comment by EfficiencyVI** [comment]
The problem is that this item is nowhere explained and only causes confusion for no reason. You can look up the other fragment in NEI where it is explained.
