### ISSUE TITLE
Swift Movement Quest is Glitched.

### ISSUE THREAD

**Issue by ktlevesque** [SnowShock35/Obscurity#175]
It won't allow me to Claim Reward.

**Comment by LyraelRayne** [comment]
Your inventory most likely doesn't have room for the reward. Because the swiftness potions don't stack you need 9 free inventory spaces in order to be able to claim the reward.

**Comment by LyraelRayne** [comment]
@SnowShock35  @johnnymobbins  TBH I think we should do something about this quest. I can see it catching people out just because of the very large (around 12?) number of slots that need to be open in order to claim the reward. I know it took me a while to work it out the first time!
