### ISSUE TITLE
Forge error concerning CoFHCore

### ISSUE THREAD

**Issue by ThatGuy01001010** [SnowShock35/Obscurity#176]
After overriding the files in my folder, I tried to launch minecraft and this error popped up:

"Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found

CoFHCore : any

The file 'logs/fml-client-latest.log' contains more information" (log following, sorry for bad formatting)

{Switched to a pastebin ~AK}

http://pastebin.com/HWd0QgLc

**Comment by CHEaZITS** [comment]
I am having that same problem. I'm not sure if I downloaded the Pack into the game right.

**Comment by LyraelRayne** [comment]
What do you mean by "overriding the files in my folder"?

**Comment by SnowShock35** [comment]
@ThatGuy01001010 @CHEaZITS  This is just an error downloading packs. Just try again.

**Comment by LyraelRayne** [comment]
Closing as it seems to be an individual issue and no further discussion has occurred.
