### ISSUE TITLE
Crashing upon exiting a compact machine (not 100% of time)

### ISSUE THREAD

**Issue by MonthOLDpickle** [SnowShock35/Obscurity#177]
Fastcraft is enabled. Sometimes when I exit my compact machine the game CTD and the launcher pops back up.

Here is a pastebin of the log: http://pastebin.com/e8kZFQkc

**Comment by AKTheKnight** [comment]
Seems to be an issue with progressive automation rendering in something

**Comment by MonthOLDpickle** [comment]
So far after removing that small 4x4 tree farm and put it in it's own machine. Also took out all machiens from within each other.

**Comment by MonthOLDpickle** [comment]
Okay even with it not in the world got same crash!

**Comment by MonthOLDpickle** [comment]
No progressive automation present I got it many times: http://pastebin.com/C0RNS2wn

**Comment by MonthOLDpickle** [comment]
Now I can't even log into this world. I am done. I don't have an PA stuff in use or down and in a chest. WHY!?

**Comment by LyraelRayne** [comment]
Related to https://github.com/SnowShock35/Obscurity/issues/179
Related to https://github.com/Vanhal/ProgressiveAutomation/issues/171
Fixed in Progressive Automation version 1.6.27

**Comment by SnowShock35** [comment]
Updated to latest Progressive Automation in 1.1.16. Fixing this issue
