### ISSUE TITLE
Dupe bug with Nether Gate

### ISSUE THREAD

**Issue by NthPortal** [SnowShock35/Obscurity#183]
Crafting 2 (partially used) Nether Gates together to combine their durability does not use up the original items (but does reduce their durability slightly as if you were using them in a regular recipe).

**Comment by SnowShock35** [comment]
#86

**Comment by NthPortal** [comment]
I do not believe it is the same bug.
To clarify, I'm referring to crafting two Nether Gates together similar to how one would craft two partially used pickaxes together to repair them. While it's possible that the cause of the bugs is the same, it seems unlikely to me. Here are some example pictures: [before](https://gyazo.com/3a142ff13cab517e86124ac80eadfb00), [after](https://gyazo.com/19de18ad31735d79fd971e69d5794c53), [a lot after](https://gyazo.com/9bf7e061bf0411df1ec0873a879347e4).
To be honest, it seems like more of a mod bug than a modpack bug, but I've been unable to find anywhere to report issues for the mod.

**Comment by LyraelRayne** [comment]
If you look at the Curse page for No Nether Needed you'll see that @SnowShock35 is listed as the author ;)

**Comment by SnowShock35** [comment]
@NthPortal Okay will try look into this

**Comment by KakesRevenge** [comment]
Ahhh okay thx for that ill try to fix it in next version :)
