### ISSUE TITLE
World backup bug/issue

### ISSUE THREAD

**Issue by Megachuggayoshi** [SnowShock35/Obscurity#184]
when I go to load up my worl it will pop up with  A message that says 

Forge Modloader  detected that the backup level.dat is being used  
this may  happened due to a bug or corruption continuing can damage  your world beyond  repair or lose data / progress   It is recomened that you make a backup before continuing   

{yes}                            {no}

no matter what  button I press it just sends me to the main menu and just sits there doing nothing and yes I have made a back up

Please help

**Comment by LyraelRayne** [comment]
Usually this sort of message means that your world has somehow been corrupted. Because AromaBackup is included in this pack, your world will have been backed up in the <obscurity installed dir>/backups folder. Your best bet is to try and find one of those which isn't corrupted and hasn't lost too much of your progress. Sorry :(

**Comment by LyraelRayne** [comment]
You may also wish to try the alternate solution from this reddit: https://www.reddit.com/r/feedthebeast/comments/2yiire/not_quite_sure_where_to_put_this_as_its_not_a/

"I know this is abit old but I got the same problem today and fixed it. All I did was made a back up of my world restarted the server with a new world, then dragged all the stuff from my old world into the new one. It worked but I lost all my inventory."

**Comment by Megachuggayoshi** [comment]
Ok thanks    :/

**Comment by LyraelRayne** [comment]
I'm going to close this now as it isn't something that can really be fixed by us. Good luck restoring your world!
