### ISSUE TITLE
glowstone nooks

### ISSUE THREAD

**Issue by tibblaye** [SnowShock35/Obscurity#185]
glowstone books and other mutipart mirco blocks for glowstone should be nerfed its kinda easy to get a  lots of them and can be picked up and replaced

**Comment by LyraelRayne** [comment]
What version? In 1.1.15 no multiblocks should be giving off any light.

**Comment by SnowShock35** [comment]
Already done in 1.1.15.

- However **DO NOT** use this version yet. 1.1.16 will be out soon ;)
