### ISSUE TITLE
Glowstone drop chance excessively low and cannot be silk touched

### ISSUE THREAD

**Issue by LyraelRayne** [SnowShock35/Obscurity#186]
I just broke a stack of glowstone with a Tinker's pickaxe and got 57 dust + 64 glass. That was after breaking about 15 with no glowstone drop. This seems excessively low. I spoke to @SnowShock35 and he seems to think it should be more.

Also as noted by PrometheanSky on the FTB forum in silk touch is not working with glowstone. Again this doesn't seem right. 

"I normally don't complain about decisions made by pack authors (though I have on occasion expressed a personal dislike), but not being able to silk touch glowstone is BS of the highest order. I'm assuming that it is to keep it from being used as mobile lighting, but we already have easier to use mobile lighting in the form of invar torches and interdiction torches.

And if it is really that important, how about this; make it so silk touch spits out 4 glowstone dust and a glass (as opposed to the current glass and rare glowstone dust), remove the crafting table recipe, and make it so that 4 glowstone dust + glass in an induction smelter = glowstone block. That would remove the ability to casually pick it up and re-place it."

**Comment by SnowShock35** [comment]
aa73c33212516d2b71a3bc58c6e2a1b0121ea856

Fixed by @VikeStep in https://github.com/VikeStep/Obscurity-Tweaks/

**Comment by SnowShock35** [comment]
https://github.com/VikeStep/Obscurity-Tweaks/commit/3d918b1588880f74f1b6316727268391f48d8ab5 Our good friend @VikeStep has fixed this for us :smile: Will be available in 1.1.16
