### ISSUE TITLE
Warp book in Thaumic Restorer = Free Ender Pearls

### ISSUE THREAD

**Issue by LyraelRayne** [SnowShock35/Obscurity#189]
From gijsc1 on FTB forum:

>i just discovered a broken way to get tons of ender pearls verry fast.
>the warp book uses ender pearls as fuel and tracks its fuel as a damage value.
>using the thaumic repairer you can "repair" it and that will fill it with 16 ender pearls for only a few >points of instrumentum.
>someone should probably fix this.

I have confirmed this.

**Comment by SnowShock35** [comment]
Re-Writing this issue for clarity of issue.
