### ISSUE TITLE
Tinker tools on compact machines

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#19]
Breaking compact machine with tinker pick doesn't drop anything

**Comment by johnnymobbins** [comment]
Tested with 3 different tinkers picks. All worked for me.
Can anyone else confirm this?

**Comment by AKTheKnight** [comment]
This was reported to me on the group skype, If no more info comes I would presume not an issue

**Comment by Kemicaze** [comment]
I've had an issue with the machine jumping several blocks away when broken, (maybe 5 or 6 blocks). The first one has a big change of dropping in the void hole. So big I activate magnet mode right before I mine it.
