### ISSUE TITLE
Can't play 1.1.15

### ISSUE THREAD

**Issue by GamingWithAGoose** [SnowShock35/Obscurity#190]
I've seen an issue identical to this been posted before but I don't know if whoever posted it fixed the issue, or found a workaround. Whenever I try and load the 1.1.15 version it gets stuck at Jared's Map Downloader and then says that FTB has stopped responding. I've tried reinstalling Obscurity completely and updating it from the past version but both didn't work. How would I get around this?

**Comment by SnowShock35** [comment]
@GamingWithAGoose It's possible to launch the game but for now please stick with 1.1.14.

Thanks

**Comment by SnowShock35** [comment]
This is a duplicate issue of #154 And is fixed in 1.1.16
