### ISSUE TITLE
EnderIO Farming Station and Octadic Capacitors

### ISSUE THREAD

**Issue by njetson** [SnowShock35/Obscurity#203]
place an octadic capacitor in an enderio farm and it won't remain on when in always active mode.  cycling modes will cause it to turn on momentarily then turn off.  scaling down the capacitor gives the expected result and farming station remains on.

**Comment by LyraelRayne** [comment]
Works fine for me. Are you sure you're supplying it with the required 100RF/tick? Remember that the capacitors increase the power consumption rate as well as the effectiveness of the machine.

**Comment by LyraelRayne** [comment]
Also could you throw us a screenshot of your farming station gui? So I can check what kind of tools you have in there in case it's related.

**Comment by SnowShock35** [comment]
@njetson you have one more day left to provide information else the issue will be closed as an invalid issue.

**Comment by njetson** [comment]
i think power was probably the issue, as suggested by LyraelRayne.  That build was intentionally running very lean and the behavior with turning it on and off fits this diagnosis.
