### ISSUE TITLE
Lava bug?

### ISSUE THREAD

**Issue by Immered** [SnowShock35/Obscurity#206]
I recently updated my Obscurity game on FTB to 1.1.16, and I noticed an issue with it. Lava doesn't seem to emit the same amount of light as before. In some areas, lava would light up the entire room. While in others, it barely brightens up the blocks around it.
I have tried to update the lava blocks (right clicking, breaking/placing nearby blocks, placing lava down, etc), but nothing seems to make them bring their light level back to what they should be.
In the end, I decided to downgrade back to 1.1.14, in which lava was working correctly, but the bug seemed to have stayed on my world (which is probably due to the 1.1.16 version updating my world and lava).

Help would be extremely appreciated (as most of my light sources are lava-based), and if I am doing something wrong, please inform me.

Thank you!

**Comment by SnowShock35** [comment]
Hi @Immered

So light level of lava is correct in 1.1.16 it is not a bug we were just unable to change it in an earlier update so the lava will take time to update to the new light level. If you have used it to light your Base I understand this could be frustrating and your more than welcome to revert the change in Obscurity/config/sprinkles_for_vanilla.cfg toward the bottom you'll see all the light level changes. Just keep in mind it could break the balance if you change things. Hope this helps.

Snow

Lead Pack Developer
