### ISSUE TITLE
JhonnyMobbins grave

### ISSUE THREAD

**Issue by Kemicaze** [SnowShock35/Obscurity#21]
There is a JhonnyMobbins grave at X955, Z219, Y82 (Next to the Sarahara compressed machine).

**Comment by AKTheKnight** [comment]
What's in the grave?

**Comment by Kemicaze** [comment]
His head, nothing else...

**Comment by AKTheKnight** [comment]
Can you get the co it's? It can be removed for next map change

**Comment by AKTheKnight** [comment]
*coords

**Comment by johnnymobbins** [comment]
Fixed
