### ISSUE TITLE
Can't join single player worlds or servers

### ISSUE THREAD

**Issue by SherlockShears** [SnowShock35/Obscurity#214]
For some reason, I am unable to join and servers or single player maps while having the Optifine mod installed. Is there a reason why it doesn't work with Optifine or is it just a bug?

**Comment by LyraelRayne** [comment]
I'm not sure but you wouldn't want Optifine anyway. It causes spiders with excessive health to spawn and one-shot you. (I'm not kidding! https://github.com/rwtema/extrautilities/issues/483).

Can you pastebin a log from when it fails? I played for quite some time using Optifine before I found out that it was making the game about 1000x harder.

**Comment by SnowShock35** [comment]
@SherlockShears This is a notice to let you know you have 96 hours till this issue is classed as invalid and will be closed. Please provide @LyraelRayne with the details he has requested.

Thanks
SnowShock
