### ISSUE TITLE
Smeltery - Pulverized Coal(Thermal Foundation) Stalls

### ISSUE THREAD

**Issue by mesmerwolf** [SnowShock35/Obscurity#218]
Hello while playing multiplayer, my friend and I discovered that when you put Pulverized Coal into the Smeltery, it will smelt halfway and then stall out. It will just sit there and consume lava but will not finish smelting.

**Comment by Arphahat** [comment]
Ah, this isn't a bug.  You need something hotter than lava to melt the coal.  Look at the NEI and you'll see it is much higher temp than other things. Liquid pryox (or something like that) is what is required.

**Comment by mesmerwolf** [comment]
Ah I will look into it then. Thanks.

**Comment by LyraelRayne** [comment]
Closing as it's not an issue with the pack.
