### ISSUE TITLE
Magical Wood Crafting Recipe x3 in AE2 System

### ISSUE THREAD

**Issue by JohnnyBsKillz** [SnowShock35/Obscurity#221]
Discovered a weird glitch. If you put a magical wood recipe into an AE2 system it displays as crafting 3 magical wood. It will only craft the one if you pick it up but if you use a pattern it does craft 3.

**Comment by SnowShock35** [comment]
The output amount of magical wood depends on the enchantments used to make it. For instance if I use 4 x Efficiency 1 books I'll most likely get 1 magical wood from crafting it.
However, If I use 4 x Silk touch I books I'll get close to a stack.

This is intended
