### ISSUE TITLE
Update from .15 to .16 , Quadrum textures missing

### ISSUE THREAD

**Issue by daeo** [SnowShock35/Obscurity#223]
I updated the pack from .15 to .16 and noticed that the blocks and item textures are missing.  The unlit torch is blank, mixed compound is 4 colors.

**Comment by SnowShock35** [comment]
Hi @daeo, 

Thank you for reporting this to me. Could you do a quick check to see if...

* mixed_compound.png exists in \config\Quadrum\block\textures
* unlit_torch.png exists in \config\Quadrum\item\textures

If you need further help, feel free to reply to your issue here.

**Comment by daeo** [comment]
Yes both files exist, as well as the luminite_ore.png file as well (which is also not displaying)

**Comment by SnowShock35** [comment]
Hi @daeo,

Interesting :confused: Could you see if \mods\Quadrum.jar exists and if there are any .json files in the block and item folders within the Quadrum folder you checked earlier

**Comment by daeo** [comment]
Quadrum-1.7.10-1.2.0.B13-universal.jar is there in the path you asked for.both paths have .json files for each item/block that is not showing up.  Did you need any screenshots of anything?

**Comment by SnowShock35** [comment]
Could you send me the entire quadrum folder from your config folder please?

**Comment by daeo** [comment]
I've sent you an email with a .7z (7zip) compressed file containing the dir you requested.

**Comment by SnowShock35** [comment]
Hmm this is very weird :/ What launcher are you using to get the pack?

**Comment by daeo** [comment]
The FTB launcher, 3rd party pack.  I had my save on 1 pc and moved the save to another pc.  Both were selected to use "Recommended", so I am not sure if it is now save related?

**Comment by daeo** [comment]
I am going to launch a new game real quick to check.

**Comment by SnowShock35** [comment]
Okay if the FTB Launcher still does not work try using CurseVoice - http://beta.cursevoice.com/ Just like installing any other minecraft launcher and there are plenty of tutorials out there I'm sure of it. Then once you've done that search for Obscurity under the Browse all modpacks button and click the install button, wait for it to install then go ahead and give that a shot. ;)

**Comment by daeo** [comment]
It is blank even on a new save.  I am going to see about reinstalling the pack first then try curse.

**Comment by daeo** [comment]
We should be able to close this, a new install fixed this.  Sorry to waste your time.

**Comment by SnowShock35** [comment]
Absolutely no problem dude. Glad you've fixed it =D
