### ISSUE TITLE
MC Tower Defense - Iron Spike Quest - Items not updating quest correctly

### ISSUE THREAD

**Issue by shnelle** [SnowShock35/Obscurity#224]
The quest calls for you to make 4 iron spikes.  The recipe makes 4.  However when I made them the quest only counted one of them.  There is no manual detect to correct it.  

I used a Tinker's Crafting Station to make them.  The crafting station is in the corner of a Big Compact Machine.  It has the quested Market on one side and a Giant Compact Machine on another.

I then tried the same recipe in a normal crafting table in the middle of the same Big Compact Machine with nothing on any side, and it worked.  It gave me all the rest of the quest counters.

**Comment by AKTheKnight** [comment]
Yeah I think that's a HQM bug

**Comment by wlhlm** [comment]
Yep, it's a known bug with the used version of HQM. See #208

**Comment by AKTheKnight** [comment]
Thank you @wlhlm I'd had a look but I couldnt see it
