### ISSUE TITLE
Can't Open My World

### ISSUE THREAD

**Issue by Pheonix144** [SnowShock35/Obscurity#225]
When I select my world it takes me back to the main menu why is it doing this?!

**Comment by AKTheKnight** [comment]
Is it crashing or is anything being said in console? Try copying the log to us so we can look at it

**Comment by Pheonix144** [comment]
I can get onto the game its opening the world which is the problem 
I never used to have this problem

**Comment by Pheonix144** [comment]
i have got it from when i select my world sorry it over so many pictures

**Comment by Pheonix144** [comment]
![picture2](https://cloud.githubusercontent.com/assets/16413187/11981702/f79e7206-a99c-11e5-8d92-93fcc15cdf41.png)
![picture3](https://cloud.githubusercontent.com/assets/16413187/11981701/f79df36c-a99c-11e5-997a-2eaa8f3a801c.png)
![picture4](https://cloud.githubusercontent.com/assets/16413187/11981703/f7a173a2-a99c-11e5-8786-8d7a4b8d5f4b.png)
![picture5](https://cloud.githubusercontent.com/assets/16413187/11981705/f7a41de6-a99c-11e5-8eb8-694d23ab03a6.png)
![picture6](https://cloud.githubusercontent.com/assets/16413187/11981706/f7a52e34-a99c-11e5-9fb0-b90b6d51ec3a.png)
![picture7](https://cloud.githubusercontent.com/assets/16413187/11981704/f7a23422-a99c-11e5-88b7-86f215a9a92f.png)
![picture8](https://cloud.githubusercontent.com/assets/16413187/11981707/f7b3bf4e-a99c-11e5-8a61-42a72b0a9c93.png)
![picture1](https://cloud.githubusercontent.com/assets/16413187/11981708/f7b515ba-a99c-11e5-8ab7-02f1b97a05b8.png)

**Comment by SnowShock35** [comment]
@Pheonix144 Phoenix can u please copy and paste that log and send me a link to it via http://www.pastebin.com

**Comment by Pheonix144** [comment]
it wont let me put the imiges on it

**Comment by Pheonix144** [comment]
if you give me a email, I could send it to you via that mabey

**Comment by SnowShock35** [comment]
@Pheonix144 I don't want images. I need a copy of the log in text form. Load up the game and try to load your world then copy the log from inside that minecraft launcher window and paste it on pastebin.com and then submit the paste then reply to this issue with the link to that paste.

**Comment by Pheonix144** [comment]
oh sorry

**Comment by Pheonix144** [comment]
http://pastebin.com/rbWxbzry

**Comment by LyraelRayne** [comment]
Looks like either one of the mod JARs got messed up or your world is corrupted. Would you make a new world and see whether that loads? From here the process could take one of two paths:

If a fresh world DOESN'T work chances are your installation has issues. That's a good thing, it means your world is probably fine. The next step is to download a fresh copy of Obscurity and copy your world folder into the fresh installation. (Close Obscurity first)

If a fresh world DOES work then you'll need to do the following (after closing Obscurity):
1. Copy your world folder to a safe place
2. find the lates backup in <obscurity>/Backups/<your world name>
3. Unzip the backup into your world folder. This will restore a backup version of your world which will hopefully be fine.
4. Load your world.

**Comment by Pheonix144** [comment]
I have tried copying file into new obscurity but it it doesn't work

**Comment by Pheonix144** [comment]
If it helps I'm opening the game via the program curse

**Comment by Pheonix144** [comment]
I think my world was corupted as when when I took the save out I could make a new world and it would take me into the world unlike before.
Thank you for helping me and creating a great game.
Also is is posible to get a lily pad in the game ?

**Comment by LyraelRayne** [comment]
I don't think it's currently possible to get a lilypad. 

If you've invested a significant amount of time in the game then you may wish to review what I wrote above about loading a backup. Otherwise, good luck with your fresh world! I'm going to close this now as it's been determined that it's an issue with your world save rather than with the modpack itself.
