### ISSUE TITLE
Unavaible to launch world.

### ISSUE THREAD

**Issue by jesper1423** [SnowShock35/Obscurity#226]
Everytime I open up a World, is comes to the loading screen saying "Building Terrain" after a few seconds the text disappears but the dirt backround is still there, then the text "Shutting Down Internal Servers" comes up and the game freezes. Thanks for reading

**Comment by AKTheKnight** [comment]
Could we please get a copy of the logs?

**Comment by jesper1423** [comment]
Crash log
https://www.dropbox.com/sh/6jjcczfsguy7m2q/AADH2ksbDPpY6tVDy6OODTFJa?dl=0
Not sure if that's the right one tho.

Got the regular log for it here
https://www.dropbox.com/s/avn9myf15rvo18w/2016-02-03-1.log.log?dl=0

**Comment by AKTheKnight** [comment]
Hmm. Seems to be saying you ran out of memory. How much ram do you have in your pc? And how much is allocated?

**Comment by jesper1423** [comment]
I have 8GB RAM  and 5.5GB is allocated to the Curse Launcher.

**Comment by AKTheKnight** [comment]
Looking at the log it looks like you might have made a little mistake with the flags:
`Memory: 59274680 bytes (56 MB) / 477626368 bytes (455 MB) up to 477626368 bytes (455 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5632m -Xms256m -XX:PermSize=256m -Xmx512M`

Fairly certain they need to be capital "M"'s for the ram allocation. (I might be wrong. If so oops)

**Comment by jesper1423** [comment]
I changed the lovercase m's to capital ones, and the World still does not open up?

**Comment by AKTheKnight** [comment]
Hmm. That's as much help as I'm able to give. I'll give @SnowShock35 a poke and ask him to have a look for you :)

**Comment by jesper1423** [comment]
Thanks for trying man! I really appreciates the help! Would really like to play this pack.

**Comment by SnowShock35** [comment]
Hey @jesper1423 so from what I can tell the issue you're having is due to memory and java arguments. Would you be able to do the following things for me:

* Sceenshot the CurseApp Minecraft settings tab (Example: http://prntscr.com/9yq288)
* Verify that your system memory is indeed 8GB (Example: http://prntscr.com/9yq3us)

Once you've done these, reply with your screenshots and I'll try to help further solve your issue. 

Cheers,
SnowShock35.

**Comment by LyraelRayne** [comment]
You have two Xmx arguments. The second one takes priority. You have therefore allocated 512 meg as the maximum heap memory size. I would suggest removing that one and leave the 5 gigabyte one (which could be rewritten as 5g, if you like)

**Comment by SnowShock35** [comment]
Thanks @lyraelrayne for confirming that. I was going to suggest that just wasn't 100% sure that was the issue.

**Comment by jesper1423** [comment]
Curse app minecraft settings: http://prntscr.com/9z17kv

System memory proof: http://prntscr.com/9z185n (In Swedish but you probably know what's what.)

And I tried to remove the second JVM Arguement, didn't work.

**Comment by SnowShock35** [comment]
@jesper1423 

Okies for starters I'd advice sticking the ram slider in the middle of the recommended section unless you're using a 32x32+ resource pack. 

Secondly, add the following jvm arguments:

`-Dforge.forceNoStencil=true -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10 -Djava.net.preferIPv4Stack=true`

**Comment by jesper1423** [comment]
Should I put the JVM Arguments in the curseApp settings or in the minecraft launcher?

**Comment by SnowShock35** [comment]
@jesper1423 In the Curse App settings always (It then injects them into the launcher)

**Comment by jesper1423** [comment]
I got into the World, but I had this extreme lag (which I shouldn't have) then the game exited itself, reopened to the pause menu, then turned blackscreen. Now the Minecraft.exe is freaking out.

Help

**Comment by SnowShock35** [comment]
Hmm okay, would you be able to send us a copy of your world save please?

**Comment by jesper1423** [comment]
I do not know why, but I can't send the file. (?)

:

**Comment by SnowShock35** [comment]
@jesper1423 Okay so go to where the save is and zip it up then upload it to dropbox and send us a link to that zip ;)

**Comment by jesper1423** [comment]
Couldn't even upload it to Dropbox (forgot to tell ya).

**Comment by jesper1423** [comment]
Tried to email it to you, but the folder is to big (162,416kB)

**Comment by SnowShock35** [comment]
Oh well that's odd :/

**Comment by SnowShock35** [comment]
hmm
could u maybe try google drive or uploading it here (if that's possible)

**Comment by jesper1423** [comment]
It's getting uploaded to dropbox right now, not sure if it'll work or not.

**Comment by SnowShock35** [comment]
ah okay

**Comment by jesper1423** [comment]
https://www.dropbox.com/sh/pjocqn56ztwdkhx/AACe4qGHxk9fJEsjRoukP1sia?dl=0

**Comment by SnowShock35** [comment]
cheers

**Comment by SnowShock35** [comment]
@jesper1423 I'll take a look at it asap and see if I can't figure out the problem

**Comment by jesper1423** [comment]
It just crashed because it ran out of memory, so I don't know. (?)

Thank you for taking your time trying to fix this problem for me! Really appreciates the help from you! :)

**Comment by SnowShock35** [comment]
@jesper1423 Do u have a base location you know of?

**Comment by SnowShock35** [comment]
Hey @jesper1423 

Okay dude the best advice is to make sure you have the settings I suggested above, delete the instance and make a fresh install (Don't add any additional mods etc.) and try create a world and see if it loads. If you're still having the problem then let me know and send us any crash reports or logs. 

Cheers,
SnowShock.

**Comment by jesper1423** [comment]
Log:  https://www.dropbox.com/s/k7tfyksrtustpea/latest.zip?dl=0

Just froze when I entered the world, and I've got no crash log.

**Comment by SnowShock35** [comment]
That log shows nothing, it's perfectly normal besides internal server lag which is expected.

@jesper1423 Is that from a completely fresh install?

**Comment by jesper1423** [comment]
It is yes, and I have no other information from loading up that World.

**Comment by SnowShock35** [comment]
@jesper1423 Hmm :/ It just doesn't make sense why that's happening do you have a list of pc specs?

**Comment by jesper1423** [comment]
Processor:  Intel Core i5-3350P CPU @ 3.10GHz 3.10GHz
RAM:  8GB
Graphic Card:  Radeon R9 270 DirectCU II OC (with GPU Tweak)

**Comment by jesper1423** [comment]
And neither do I know why this is happening. :(

**Comment by SnowShock35** [comment]
@jesper1423 I doubt it would make a difference but could you give two things a try and test between trying both of them and do them in order: 

1. Uninstall all versions of Java on your PC as of right now and reinstall the Top link here (Windows Online) http://www.java.com/en/download/manual.jsp Then try re-run it.

2. If that doesn't work, Download and install the FTB Launcher and run the pack on that (It's on the third party pack tab)

**Comment by jesper1423** [comment]
What if I have the FTB Launcher, could I do that first? As I know the CurseApp is a bit buggy still?

**Comment by jesper1423** [comment]
Should I do it with a new world?

**Comment by SnowShock35** [comment]
yes 
definitely

**Comment by SnowShock35** [comment]
That world you sent me last night appeared new anyways, was it not?

**Comment by SnowShock35** [comment]
If not then try a new world just by default

**Comment by jesper1423** [comment]
I did unistall all the java updates, installed the one you sent and the game didn't work. I'll try in FTB Launcher. (It seems better because it's not in an Alpha and has less bugs)

**Comment by jesper1423** [comment]
Detected 32-bit Java on 64-bit operating system.
64-bit Java is required to use largest modpacks.
Memory will be limited to 1 GB with 32-bit Java
If you have issues, please try the FTB Lite packs or other smaller packs.
This problem can be fixed by downloading and installing 64-bit java from Oracle's website.
After installing 64-bit java remember to increase memory allocation to 2-4 GB in options tab

**Comment by jesper1423** [comment]
Should I install the 64-bit or stay with this one?

**Comment by SnowShock35** [comment]
install the 64-bit sorry I forgot the online version detects based on browser I believe. so yea go back to the same java link and get the offline 64bit windows version

**Comment by jaredlll08** [comment]
Ok so, please can we get your latest java arguments, and open a cmd, run "java -version" and give us the output

**Comment by SnowShock35** [comment]
@jesper1423 Ignore jared until you've tried What I've said then try what he said

**Comment by jesper1423** [comment]
Well launching the modpack in the FTB Launcher DID indeed fix it all. I never realised it was on the FTB Launcher. So thank you all on this thread for the help and I'll write (either on this thread or Another/new  one) if some kind of problem pops up.

                                                        SO THANK YOU ALL GUYS! :D

**Comment by SnowShock35** [comment]
@jesper1423 No worries glad to help :smile:
