### ISSUE TITLE
Can't complete quest

### ISSUE THREAD

**Issue by KacpixPl** [SnowShock35/Obscurity#26]
Can't complete the /dev/null quest. Recommend changing it to a detection task rather than a crafting task.

**Comment by Kemicaze** [comment]
Confirmed, here. not completing when /dev/null is crafted.

**Comment by SnowShock35** [comment]
Johnny will fix this hopefully for 1.1.9

**Comment by SnowShock35** [comment]
Fixed in 1.1.9
