### ISSUE TITLE
Entering Compact machine sets EXP to 0

### ISSUE THREAD

**Issue by Kemicaze** [SnowShock35/Obscurity#27]
...

**Comment by AKTheKnight** [comment]
@SnowShock35 Presuming mod update needed

**Comment by Kemicaze** [comment]
and it doesn't return when you leave the cube again.

**Comment by Kemicaze** [comment]
The correct amount of exp is show when the exp bar is updated. (Did a bottle o enchanting and it came back with the correct amount.)

**Comment by AKTheKnight** [comment]
okay, so it is a graphical issue. I'll msg the mod author

**Comment by johnnymobbins** [comment]
Has the CM dev been notified about this?
