### ISSUE TITLE
New world starts in creative, buried in the ground

### ISSUE THREAD

**Issue by feralferret** [SnowShock35/Obscurity#3]
The game is in creative mode when you start a new world, and you start off about 6 blocks underground outside of the tower.

**Comment by AKTheKnight** [comment]
thanks for letting us know, we'll get that fixed

**Comment by johnnymobbins** [comment]
Can you please try and replicate that? We cant see too see that same error.

**Comment by SnowShock35** [comment]
Please provide more information on your issue.

**Comment by AKTheKnight** [comment]
Closing as nobody can reproduce this and issue appears to be fixed
