### ISSUE TITLE
Chisel Torches?

### ISSUE THREAD

**Issue by johnnymobbins** [SnowShock35/Obscurity#33]
If torches are Chiseled they no longer break on pickup.

**Comment by SnowShock35** [comment]
Fixed! 1.1.8

**Comment by Nagapito** [comment]
Unless you remove Jack o' Lanterns... Its kinda indifferent since the torch gives light in a small radius. 
The Jack o Lanterns are giving glowstone level light, are breakable and accessible early game...

**Comment by SnowShock35** [comment]
Fixed in 1.1.8
