### ISSUE TITLE
Plants not growing in deep dark

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#34]
Trees and food crops don't seem to grow

**Comment by AKTheKnight** [comment]
"the only things that are growing is sugarcan, cactus and nether wart"

**Comment by johnnymobbins** [comment]
Everything should work. Check your light level. Try jack o lanterns

**Comment by AKTheKnight** [comment]
Issue #10 links in with this

**Comment by johnnymobbins** [comment]
Always ensure light level is correct.
