### ISSUE TITLE
Pits of hell

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#35]
First item for quest is "invalid item"

**Comment by SnowShock35** [comment]
What do you mean by this?

**Comment by AKTheKnight** [comment]
Someone posted it on the forum.

**Comment by SnowShock35** [comment]
There is no quest called this. Ask for more information please

**Comment by Nagapito** [comment]
He later edited the post to "Gateway to hell"

**Comment by SnowShock35** [comment]
Ah right. I think I fixed that so yaay! :D
