### ISSUE TITLE
Orespawn

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#36]
So, it seems ore spawn is very low on some ores:
-Less actual stone for the ores to spawn in meaning the small chances are getting even lower

"So... I was getting really frustrated with my search for shiny ore so I decide to do a little map analysis..

Using cofh tools, I removed all the shiny ores in a square radius of 100 blocks from me. That is an 200x200 area. Since it can spawn from y level 5 to 30, that is a volume of 200x200x25 which is 1 million blocks!!!

It only removed 101 blocks! In 1 million blocks there are 101 shiny ore blocks! That is 0,01%!!

Dont you think the spawn chance needs a little boost? Its not like its going to break it to much since there is enough ferrous to get shiny ore later.
Or maybe other ores need a little nerf so more stone is available to spawn, since the chance should actually be 0,04% (3 blocks in a 16x16x25 volume) but with so many non-stone blocks, it just fails to spawn them.

The problem is all the progress that is halted in the quest book while we try to get the 10 shiny blocks. I could start building machines and all the stuff but I would rather do the normal progression with the quest book instead of finding the 10 blocks in a couple of days and suddenly unlock 20 already completed quests...

The only downside is the requirement for a world reset, since the retrogen just did nothing to me...

ps: While at it, also check lapis... is spawn rate is also kinda low... maybe due to the high density of other ores too..."

**Comment by AKTheKnight** [comment]
Using an Ender quarry Yoshii (bugtester) mined 30,000 blocks and got 3 shiny ore

**Comment by SnowShock35** [comment]
I will add some sort of recipe to try and help this but cannot reset the map so that's all I can do I'm afraid.

**Comment by SnowShock35** [comment]
Added some shiny and lapis to a few of the quests for now. Recipes will be added next time. In our ToDo List ;)

**Comment by Nagapito** [comment]
While looking at the recipes, think about the quartz problem since the world was generated without OverworldQuartz...

**Comment by SnowShock35** [comment]
The overworld quartz from No Nether Needed was in the map generation from the beginning but the ore changed id two versions ago when I updated the mod so it obviously would of stopped generating if you went far out but that's now fixed so if u did explore in 1.1.7 you might not have it in a few places but not much.

**Comment by Nagapito** [comment]
Are you sure? I found none in the 1.1.7 map in the already generated chunks. I will check again in a test world with COFH clear blocks but I dont remember seeing it the previous time I run it in the past

**Comment by Nagapito** [comment]
Yep, no overworld quartz in the map, so no way of getting qartz except the little amount in the nether cube. Also checked on 1.1.9  map

**Comment by SnowShock35** [comment]
Hmmm okay. This is a rather big problem. Will look into it as much as I can but not sure I can do anything at this stage :/

**Comment by Nagapito** [comment]
I just had an idea to this problem. 

- Shiny ore is scarse but quest requirements were lowered and we get a bunch of it and later we have an ender quarry. Done

- Lapis, there is some, not much but an ender quarry can solve it. Done

Quartz. Now... map got bugged and there is no quartz... It might be just me but I always lookt at quartz and marble and relate both, maybe due the quartz blocks... Maybe, add a recipe to pulverize marble into quartz? Or some way of changing AE quartz into nether quartz? Like... smelting it with netherack in the induction smeltery?

**Comment by Nagapito** [comment]
One more note: 

In case you decide to regen the world ores for a future version, take a careful attention to dirt. Its generating way to much dirt, specially on lower levels, taking away the spawning chance for the rare ores. If the world generation follows the order on the file, just move the dirt to the end of the file, so it allows all ores to be generated first.

**Comment by SnowShock35** [comment]
Written up into a better issue with things that need doing. From now on refer to #102 for ore generation problems
