### ISSUE TITLE
Add silverfish blocks to the map generation at 5%

### ISSUE THREAD

**Issue by Nagapito** [SnowShock35/Obscurity#38]
Every time I am mining, I am always expecting the moment I will get silverfish......

Since an ore regeneration will probably be needed in the future... why not a small chance of silverfish blocks in the map? Like... below level 35, 3-4 clusters on 1-2 blocks...

Would spice the manual mining a little :)

**Comment by AKTheKnight** [comment]
Sounds like a cool idea and I would support it

**Comment by SnowShock35** [comment]
Will be added when the map reset is done further down the line. but for now it will not happen.

**Comment by johnnymobbins** [comment]
I hate those fucking things so its a no from me but happy to be outvoted.

**Comment by SnowShock35** [comment]
Will do for 1.2.0_Alpha

**Comment by SnowShock35** [comment]
Now refer to #102 for this stuff
