### ISSUE TITLE
Proper processing quest breaks progression

### ISSUE THREAD

**Issue by Nagapito** [SnowShock35/Obscurity#39]
Ender IO machines require steel and to do steel we need machines that come later in the quest path. 

Seems we could also use pyrotheum dust in the smeltery to smelt the pulverized coal but for that we need sulfur that can only be obtained with machines that also come later in the quest path. This, ignoring the fact it also requires blaze powder....

Smelting chain armor is a shot in the dark! Never had a mob with one, much less drop it....

**Comment by AKTheKnight** [comment]
Snow and Johnny will look at what can be done, other people have reported issues with steel too

**Comment by SnowShock35** [comment]
Huh I had no idea that it required pyrotheum to make steel :/

**Comment by SnowShock35** [comment]
Okay, will revert the recipes or change the melting point or something ;) - Will be done for 1.1.9

**Comment by SnowShock35** [comment]
Fixed in 1.1.9
