### ISSUE TITLE
cant buy animal eggs on market

### ISSUE THREAD

**Issue by Nagapito** [SnowShock35/Obscurity#40]
I choose the spawn egg, ex pig, give the 6 emeralds but the buy button does nothing.

Ot works fine with seeds....

**Comment by AKTheKnight** [comment]
This is a known issue that I forgot to add into here. I presume a mod update may be in order

**Comment by Kemicaze** [comment]
Confirmed in my instance.

**Comment by SnowShock35** [comment]
All I can say as of now is #blamePam :p

**Comment by johnnymobbins** [comment]
Have we contacted Pam to let her know of the issue?

**Comment by SnowShock35** [comment]
Not as of yet no

**Comment by johnnymobbins** [comment]
This has been fixed in latest release and I have double checked. Snow please include new version in 1.1.10 and close issue.
