### ISSUE TITLE
Pam's Candles?....

### ISSUE THREAD

**Issue by Nagapito** [SnowShock35/Obscurity#43]
Are the Pam's White candles supposed to give 15 light level? And be breakable?

**Comment by AKTheKnight** [comment]
Yes and yes. For now they are. I think this will change but we are waiting for something.

**Comment by johnnymobbins** [comment]
Snow, I think this recipe could be disable completely.

**Comment by SnowShock35** [comment]
Fixing for 1.1.10

**Comment by SnowShock35** [comment]
Fixed in 1.1.10
