### ISSUE TITLE
Gateway to hell quest

### ISSUE THREAD

**Issue by Nagapito** [SnowShock35/Obscurity#46]
Second step asks us to craft a nether quartz item but that is not possible since such crafting recipe does not exist. Only smelting ones.

The crafting recipe is for the nether quartz ore and even that one is not possible due the lack of overworld quartz ore in the map

**Comment by SnowShock35** [comment]
Noted, will be fixed in 1.1.10 ;)

**Comment by SnowShock35** [comment]
Fixed in 1.1.10
