### ISSUE TITLE
64 stack of torches in the starting chest...

### ISSUE THREAD

**Issue by Kemicaze** [SnowShock35/Obscurity#49]

**Comment by Kemicaze** [comment]
What more information you want. In the first chest, in the first cube, under the sign Emergency Supplies there is a 64 stack of torches inc. the normal 3 or 4 torches, so like 68 in total.

**Comment by SnowShock35** [comment]
Huh weird. Will fix in next version ;)

**Comment by SnowShock35** [comment]
Fixed in 1.1.10
