### ISSUE TITLE
Flint Mattock not registering as created for the quest

### ISSUE THREAD

**Issue by Kemicaze** [SnowShock35/Obscurity#50]
I even waited crafting it, till I got the quest in the quest book.

**Comment by AKTheKnight** [comment]
Switch to inv check instead of crafting?

**Comment by Nagapito** [comment]
NBT will just screw the detection, even for crafting. 
Instead you should detect that the player has crafted all the parts necessary for the mattock

**Comment by SnowShock35** [comment]
Will fix for next version

**Comment by johnnymobbins** [comment]
Fixed for 1.1.10
