### ISSUE TITLE
Bedrock quest

### ISSUE THREAD

**Issue by Jameskn** [SnowShock35/Obscurity#51]
http://prntscr.com/7aolmu Needs bedrock rather than jack o'lanterns for the quest in 1.1.9_beta

**Comment by Nagapito** [comment]
and... isnt the recipe with 8 torch's instead of 4 as the quest says?

**Comment by SnowShock35** [comment]
Noted, will be fixed for next version

**Comment by johnnymobbins** [comment]
Fixed for 1.1.10
