### ISSUE TITLE
Jack O'Lanterns break into pumpkins

### ISSUE THREAD

**Issue by wsetzer** [SnowShock35/Obscurity#57]
In both v1.1.9 on the FTB launcher and v1.1.10 on the Curse launcher, breaking a jack o'lantern with an axe results in a pumpkin being returned.  The quest book (and steep 8 torch crafting cost) seemed to indicate that jack o'lantern would be movable, not destroyed.  This was in a game I made starting in the v1.1.9 patch.

**Comment by SnowShock35** [comment]
So this is set like this so not a bug. However, will need to ask @johnnymobbins opinion on it and we'll update either the quest book or the drops of the jack o lantern depending on what we decide ;)

**Comment by SnowShock35** [comment]
Nope! I like how this is. Will update quest book for 1.1.11
