### ISSUE TITLE
Mobs too OP?

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#60]
"Wow!! I have full Tinker's Alloy Armor and I get one shot by a Mighty Spider?!?!? Yes I know that mobs are stronger in this dimension, but it shouldn't be a one hit kill with any armor on, maybe without."

From forum

**Comment by SnowShock35** [comment]
People keep saying they're OP but there not supposed to be easy. In some cases I still think they are too easy but will discuss somethings and what not ;)

**Comment by SnowShock35** [comment]
Meh...

**Comment by alstell** [comment]
Not sure if this counts or nor, but to put in my two cents here, I just got jumped in my base by a "normal" spider with 524288 health. The only thing keeping me alive is my torch that won't let him near me. If I get too close he one hits me. This is on the newest beta 1.1.12. 

I am all for tough, but you have to have a fighting chance.

-Avi

**Comment by SnowShock35** [comment]
@alstell I made this into it's own issue ;) #77
