### ISSUE TITLE
Quest Book reseting

### ISSUE THREAD

**Issue by chrisjayl** [SnowShock35/Obscurity#64]
The quest book resets every time i leave my save to the main menu pls help i wana track my quest that i completed

**Comment by AKTheKnight** [comment]
What version of the modpack are you using?

**Comment by chrisjayl** [comment]
v1.1.11

**Comment by chrisjayl** [comment]
i have not added any mods ether

**Comment by SnowShock35** [comment]
Hi @chrisjayl,

So this issue of yours is very strange. Can you give me the steps to reproduce and also some images of before and after. 

Thanks
-Snow :wink:

**Comment by chrisjayl** [comment]
early today i was playing and i crashed so i rejoined and my quest book was reset and i was completed with the entering darkness quest page then i crashed then i have no quests completed
but now when i leave and rejoin it is saving but when i join that save my quest book was still on the first quest.

**Comment by chrisjayl** [comment]
![2015-06-30_15 17 55](https://cloud.githubusercontent.com/assets/13124017/8443491/0bedd652-1f3c-11e5-8ac4-eddf73a64637.png)

**Comment by SnowShock35** [comment]
Was there a crash report? If so can u upload it to a pastwbin and stick the link in here

**Comment by SnowShock35** [comment]
@chrisjayl I'm still in need of more information, if there is no further information provided within 48 hours this issue will be closed.
