### ISSUE TITLE
Tinker's tools tool kit only detects oak

### ISSUE THREAD

**Issue by eslachance** [SnowShock35/Obscurity#65]
The "Starting a Tookit" quest did not detect the Stencil Table which was made with a Birch plank rather than Oak (I got the birch in a reward bag, FYI).

**Comment by AKTheKnight** [comment]
I think we have that as intentional as the player only has an oak sapling until you get past the quest and get given the other saplings. I will however talk to Johnny and Snow about it

**Comment by AKTheKnight** [comment]
Will be fixed for the next version if not already fixed

**Comment by johnnymobbins** [comment]
Fixed
