### ISSUE TITLE
Memory leak when using Compact Machines

### ISSUE THREAD

**Issue by eslachance** [SnowShock35/Obscurity#66]
Essentially, going in and out of the Compact Machine dimension causes memory usage to go up.. way up. At one point it becomes unplayable because the whole game freezes up for seconds at a time. 

This seems eerily familiar with the bug Mystcraft had in older versions, so I'm wondering if the issue is the same.

**Comment by AKTheKnight** [comment]
I think this is actually just an issue with minecraft as a whole. Everytime you change dimension there is a slight memory leak. Changing dimensions lots, as we do with compact machines would cause this issue to become worse.

I will get someone to talk to the mod author and see what might be happening

**Comment by SnowShock35** [comment]
This is a problem with the way Java/Minecraft is made. This unfortunately will not be fixable.
