### ISSUE TITLE
Can't trigger the "Nether" location in "the old portal" quest

### ISSUE THREAD

**Issue by eslachance** [SnowShock35/Obscurity#68]
I went to the nether, and was wholly unable to trigger the "Nether" part of "the old portal" quest to complete. I tried everything, including simply breaking the portal in creative to be at 0m away, nothing.

The next quest is still available, however, so it's not strictly necessary to complete it. Still, seems weird.

**Comment by SnowShock35** [comment]
Your not supposed to go to the nether. There is a cube you have to go to ;) The nether dimension should be disabled :confused:

**Comment by eslachance** [comment]
Please ignore I was playing 3 different packs and got confused. This belongs in the "Void" modpack. Ooops.

**Comment by SnowShock35** [comment]
@eslachance No worries ;)
