### ISSUE TITLE
NEI Spawn overlay

### ISSUE THREAD

**Issue by Kemicaze** [SnowShock35/Obscurity#7]
The NEI spawn overlay disables when you jump between the compact machine dimension and the Darkness dimension.

**Comment by AKTheKnight** [comment]
That's a fun one. Do you mean the F7 overlay?

**Comment by Kemicaze** [comment]
Indeed yes, the F7 one! :)

**Comment by SnowShock35** [comment]
Well there is nothing I can do about this so I will close it until the issue becomes a major noticeable problem
