### ISSUE TITLE
Unable to Activate the Division Sigil

### ISSUE THREAD

**Issue by OddinMasse** [SnowShock35/Obscurity#72]
There seems to be no way to perform the Division Sigil ceremony from Extra Utilities. The Altar needs a clear opening to the sky and that can not be achieved in the world or inside the compact cubes.

**Comment by johnnymobbins** [comment]
******************* Spoiler Alert ************************

There is a sigil hidden in one of the deep dark dungeon houses. Once you complete that quest you will get a new one than enables you to trade it for an activated one.

Updated quest will be in next version.

Thanks.
