### ISSUE TITLE
Mini Smelting quest problem

### ISSUE THREAD

**Issue by Zombarian** [SnowShock35/Obscurity#73]
The quest Mini Smelting seems to be bugged because when i craft the required item (magma crucible) it doesn't detect it.

**Comment by SnowShock35** [comment]
@Zombarian What version of the pack are you using?

**Comment by Zombarian** [comment]
I am using the recommended version in the ftb launcher. I guess its 1.1.1.2

**Comment by SnowShock35** [comment]
Recommended on ftb launcher is 1.1.11 and I believe this was fixed in the newest version but requires nether brick now which we'll add a easy recipe for in the next version. Try updating to 1.1.12 and see what happens ;)

**Comment by Zombarian** [comment]
All fixed thank you, and if you don't mind could you please answer a quick question: how do i do the quest "Cursed Rituals" I mean there is no sky in the deep dark

**Comment by SnowShock35** [comment]
@Zombarian Yeah we didn't think about that so for now either cheat it or try using the last melinium dimension if that'll work. That will be fixed for 1.1.13 ;)
