### ISSUE TITLE
Change Glowing Water recipe back to Luminite instead of glowstone

### ISSUE THREAD

**Issue by johnnymobbins** [SnowShock35/Obscurity#74]
Don't know why this was changed back! It is a VERY intended recipe. Leaving it at glowstone halts progression for some items. CHANGE IMMEDIATELY and do not make recipe changes without consulting Johnny!!!

**Comment by SnowShock35** [comment]
#blameSnow :stuck_out_tongue_closed_eyes:

**Comment by SnowShock35** [comment]
Fixed in 1.1.13
