### ISSUE TITLE
[Bug] Main menu text not adjusting correctly

### ISSUE THREAD

**Issue by SnowShock35** [SnowShock35/Obscurity#75]
The mojang text in the bottom right in version 1.1,11/12 is not adjusting it's position correctly. Fix for 1.1.13

**Comment by AKTheKnight** [comment]
#BlameSnow

**Comment by SnowShock35** [comment]
No blame Minecraft Unicode font for being weird on GUI rescale :stuck_out_tongue_winking_eye:
