### ISSUE TITLE
[Bug] Seriously overpowered spiders!

### ISSUE THREAD

**Issue by SnowShock35** [SnowShock35/Obscurity#77]
Have no idea why but several incidents of spiders with huge amounts of life and hits really strong.

**Comment by LyraelRayne** [comment]
See my detailed report on https://github.com/rwtema/extrautilities/issues/483 

Appears to be caused by Optifine.

Also for informational purposes, this appears to somewhat affect headcrumbs celebrity mobs as well, although not to the same extent.

**Comment by LyraelRayne** [comment]
This issue is caused by optifine. Optifine is not part of the pack. An issue has been logged with Extra Utilities. Closing.
