### ISSUE TITLE
Quests: 1 Bug + 1 potential bug?

### ISSUE THREAD

**Issue by rpbaxter** [SnowShock35/Obscurity#79]
1) Confirmed bug:

Version 1.1.12: Quest "Digging in the Dark!"
All ores are detected after collection except Gold Ore. I collected more ore than the minimum requirement, some before updating to 1.1.12, many after. HQM fails to recognize gold ore collection. 

2) Potential bug or just a problem? 

I read in a post on the FTB forums (http://forum.feed-the-beast.com/threads/1-7-10-now-listed-obscurity-%C2%B7-jampacked-ii-wining-pack-%C2%B7-hqm-200-quests-%C2%B7-custom-map.86908/page-12) how there were considerations being made to changing the drop rate for cotton seeds, but I am not obtaining any from tall grass. I assume that "tall grass" involves bone mealing the grass surface and then applying a second bone meal to convert short grass to a 2-block tall type of grass and then break.

I consumed over 5 stacks of bone meal attempting to get a single cotton seed with no success. Breaking short grass yields a multitude of other seeds as intended. I have attempted using an empty hotbar slot (the literal sense of the instructions "punching tall grass") for around 1 stack of bone meal so far, but still nothing.

**Comment by SnowShock35** [comment]
@rpbaxter It has to be the one tall long grass. As for it still not dropping try doing /mt seeds and see if cotton is listed and if it is just keep trying or maybe use /mt reload and then try.

**Comment by rpbaxter** [comment]
I'm unfamiliar how to do a hqm edit, but the /mt seeds did not produce a cotton seed until after I ran the /mt reload script. It's unclear how to make single block height of tall grass for me.

**Comment by rpbaxter** [comment]
Confirmed. Cotton seeds were obtained with the rest of my seeds by destroying grass. Thanks for your assistance!

**Comment by SnowShock35** [comment]
@rpbaxter No worries, yeah unfortuneatly minetweaker is a bit funky at times. so just relog or do /mt reload if u have issues and if you are still having issues then send us another issue ;)
