### ISSUE TITLE
open your eyes 

### ISSUE THREAD

**Issue by tibblaye** [SnowShock35/Obscurity#81]
the potion of weakness is not manual detecting what verison of the potion do i need?

**Comment by johnnymobbins** [comment]
Can you tell us which quest you are referring to?

**Comment by tibblaye** [comment]
the quest called open your eyes >_>

**Comment by McMorgenmantel** [comment]
FYI: It's in the Thaumcraft Quest line

**Comment by AKTheKnight** [comment]
Is this bug still there?

**Comment by SnowShock35** [comment]
Depends on whether @johnnymobbins changed that quest to nbt/metadata detection, I will poke him when he wakes to fix it ;)

**Comment by SnowShock35** [comment]
@johnnymobbins Derped, will be done for next version (1.1.14)

**Comment by johnnymobbins** [comment]
fixed
