### ISSUE TITLE
Flux-Infused tools not working?

### ISSUE THREAD

**Issue by Insufficient-Charge** [SnowShock35/Obscurity#82]
When I attempt too use the flux-infused pickaxe or shovel (not tried the axe yet) it will not mine. At all.
It does not say on the tool tip "This tool cannot mine anything" so I have no idea what the issue is.

**Comment by SnowShock35** [comment]
Will fix for the next version, sorry for this ;)

**Comment by Insufficient-Charge** [comment]
Its fine, just wanted to use them after completing the quest and found out they were useless :/

**Comment by SnowShock35** [comment]
@Insufficient-Charge Okay so this problem is caused by SquidUtils and until the mod updates I can't do anything about it. Will try fix it for 1.1.13 but no garentees

**Comment by SnowShock35** [comment]
@johnnymobbins is disabling these quests for now will re-enable for 1.2.0

Sorry about this

**Comment by Insufficient-Charge** [comment]
Its fine . . . as long as I get to use that pickaxe eventualy I'm good :D

**Comment by SnowShock35** [comment]
This will be fixed for 1.1.15_Beta ;)

**Comment by SnowShock35** [comment]
Fixed in 1.1.15_Beta

**Comment by LyraelRayne** [comment]
@johnnymobbins you might want to re-enable the quest for these now that the tools are working.
