### ISSUE TITLE
uncompletable quest 

### ISSUE THREAD

**Issue by fangz667** [SnowShock35/Obscurity#83]
the 3rd guest of the first chapter has been rendered uncompleteable as the co-ordinates are not in the book even after finding the item in the world then quest it still uncompleted

**Comment by johnnymobbins** [comment]
You need to re read the quest book. 

You need to find the cube. There are no coordinates. Follow the light below.

**Comment by fangz667** [comment]
I have already found it on two different play thoughs and still it's not completed

**Comment by AKTheKnight** [comment]
You need to then go through into the cube by right clicking on it with the gameboy tool

**Comment by fangz667** [comment]
Oooooh my mistake sorry
