### ISSUE TITLE
QDS not recognizing liquids.

### ISSUE THREAD

**Issue by OddinMasse** [SnowShock35/Obscurity#85]
For the Lava Generation quest, pumping lava into the QDS does not update nor complete the quest. I did this after using "Select Task" and right clicking the QDS with the book. Right-clicking the QDS showed the active quest as Lava Generation. I pumped the lava (all 100 buckets worth) from a Drum using Ender IO pressurized conduits.

**Comment by johnnymobbins** [comment]
Fixed.

I have tested with pressurized conduits and direct input from a portable tank. All working fine.

Will be in next version. Thanks!
