### ISSUE TITLE
Thermal Expansion "Magma Crucible" output too "Fluid transposer" input not working?

### ISSUE THREAD

**Issue by Insufficient-Charge** [SnowShock35/Obscurity#87]
When I attempt to use the magma crucible output "directly" to the fluid transposer input, it just won't work.

I ended up needing to use pipes and tanks just to get one liquid from one machine to another.

Hope this helps as a report :)

**Comment by Insufficient-Charge** [comment]
It works for any other machine input-output wise.

**Comment by SnowShock35** [comment]
@Insufficient-Charge What augments are in the Magma Crucible?

**Comment by Insufficient-Charge** [comment]
Well, the input and output tabs wouldn't be there if they didn't have the correct augments :/

**Comment by Insufficient-Charge** [comment]
I can send you screen shots if you'd like?

**Comment by SnowShock35** [comment]
@Insufficient-Charge  Please provide screenshots of the augment tab. thanks. -Snow

**Comment by Insufficient-Charge** [comment]
I will provide those but the magma crucible wouldn't work with the output to the ender io tank I have under it if it didn't have the correct augments :/

**Comment by Insufficient-Charge** [comment]
Oddly enough, it was actualy my own mistake. Sorry for wasting your time :)

I did find a bug though, and the magma crucible does not come with all of the augments needed.

I was confusing myself because the ender io tanks can pull from an inventory.

Should've done my own debugging before reporting this, sorry mate :)
