### ISSUE TITLE
Punji stick quest does not count the correct number

### ISSUE THREAD

**Issue by ctholm** [SnowShock35/Obscurity#88]
They create 5 at the time for 5 sugar cane. It says 9 are needed. Crafting 10 and it says 6 done. Crafting 15 and it completes

**Comment by Insufficient-Charge** [comment]
Its just somebody messing up they're math! Its fine! :D

**Comment by AKTheKnight** [comment]
Uhh #BlameSnow?

Seems like a math issue

**Comment by Insufficient-Charge** [comment]
True :D

**Comment by johnnymobbins** [comment]
Fixed
