### ISSUE TITLE
Bullets quest does not count correctly

### ISSUE THREAD

**Issue by ctholm** [SnowShock35/Obscurity#89]
Crafting 4 stacks of bullets completes 8/64 in the quest. It counts each crafting as one, but a crafting gives 32 bullets.

**Comment by Insufficient-Charge** [comment]
I think that this is just a misunderstanding when they made the quests, for the crafting quests, it counts per operation. They will most likely fix this in the next update :)

**Comment by Insufficient-Charge** [comment]
Just got to that quest, its true :)

**Comment by johnnymobbins** [comment]
Fixed
