### ISSUE TITLE
Barrels

### ISSUE THREAD

**Issue by KacpixPl** [SnowShock35/Obscurity#9]
You can break the barrels that are at the tower and get the infinite item barrel upgrade thing.

**Comment by AKTheKnight** [comment]
That is awesome, time to dupe everything ;)

**Comment by KacpixPl** [comment]
Best part is, you can dupe the dupe upgrades and barrels!

**Comment by AKTheKnight** [comment]
So we can be bigger dupers than Soaryn?

**Comment by SnowShock35** [comment]
I'm just gonna go ahead and #blameSoaryn

**Comment by johnnymobbins** [comment]
Replacing them as creative strong boxes
