### ISSUE TITLE
Server not starting with included world.

### ISSUE THREAD

**Issue by nicky8009123** [SnowShock35/Obscurity#90]
I installed the pack onto my server. When i use the included world it never finishes starting up. (link to log, http://pastebin.com/ZZMNS95G), but when i set the sever to generate a world, it runs perfectly fine.

**Comment by AKTheKnight** [comment]
This seems similar to a known issue that I thought had been fixed.

This could possibly be caused by missing mods as suggested in the log.

As a fix please try grabbing a world made in singleplayer and putting that in your server folder. Does that work?

**Comment by nicky8009123** [comment]
tried that, no luck. i know there are no missing mods because i  matched each one the needed to be on the server ( excluding nei, ect,) and they equaled each other.

**Comment by Insufficient-Charge** [comment]
NEI is a mod serverwise, I think . . . dunno for sure, but I'm pretty sure I've heard of some server-client issues from NEI, meaning that NEI has something to do with the server . . .

**Comment by nicky8009123** [comment]
Because reinstalling the server for some reason worked, after i tried it literally 5 times... I dont know why it worked but it did.
