### ISSUE TITLE
Boots of the traveler impossible to make?

### ISSUE THREAD

**Issue by Insufficient-Charge** [SnowShock35/Obscurity#93]
Boots of the traveler requires leather boots, which are disabled for some reason :/

**Comment by AKTheKnight** [comment]
That's most likely because snow has disabled crafting of the armour.

I presume this can be fixed in mibetweaker

**Comment by Insufficient-Charge** [comment]
Maybe tweak the "Boots of the Traveler" recipe to require hardened leather boots instead? I don't know, whatever pleases the pack makers :D

**Comment by SnowShock35** [comment]
Fixed in 1.1.13, needs some tests if people could ;)
