### ISSUE TITLE
Natural things don't growing

### ISSUE THREAD

**Issue by GustavoSousaHUEBR** [SnowShock35/Obscurity#94]
the crops don't grow, and the grass block don't grow and every modpack that i play, the natural things don't grow, what i make to resolve this problem ?

**Comment by jaredlll08** [comment]
Do they have enough light? usually things only grow if they have enough light.

**Comment by AKTheKnight** [comment]
So are you saying this is an issue in all the packs you play?

**Comment by SnowShock35** [comment]
No Information given, Being closed!
