### ISSUE TITLE
new world generates with missing blocks/items

### ISSUE THREAD

**Issue by oenone** [SnowShock35/Obscurity#95]
When generating a new world, I get a message about missing blocks/items.
Version is 1.1.12_Beta from Curse.

Missing Blocks/Items:
openmodularturrets:chamber
openmodularturrets:energeticBarrel
openmodularturrets:barrel
openmodularturrets:containmentChamber
openmodularturrets:configTab

**Comment by Insufficient-Charge** [comment]
openmodularturrets mod must not be in that version, when they are in the map upon generation.

Just my idea though :)

**Comment by AKTheKnight** [comment]
It is still in the pack. However it is updated in this version. Let me check whether it downloads correctly

**Comment by AKTheKnight** [comment]
Repeatable: http://prntscr.com/7s4vxe

Fresh install of 1.1.12 from Curse

**Comment by SnowShock35** [comment]
Fixed!
