### ISSUE TITLE
Turret Configuration Quest not completable

### ISSUE THREAD

**Issue by PyronFirewalker** [SnowShock35/Obscurity#96]
The Turret Configuration Quest is a crafting quest but the item that needs to be crafted is showing as unknown in the quest book.

**Comment by Insufficient-Charge** [comment]
Funny. worked for me :/

**Comment by AKTheKnight** [comment]
Mod was updated in 1.1.12 so may be a new item id

**Comment by johnnymobbins** [comment]
Fixed

**Comment by LyraelRayne** [comment]
This appears to be broken again. The quest is asking for a piece of bedrock now. It actually appears that in the 2.0 stream of OMT that the turret target configurator item has been removed and the turrets are now simply configured by right clicking the turret base. Perhaps the quest should simply be removed, or replaced with something else. Maybe the incendiary turret.

**Comment by SnowShock35** [comment]
@johnnymobbins is this fixed in 1.1.15?

**Comment by johnnymobbins** [comment]
No not yet, the item it relates to doesn't seem to be there anymore. I'll work on it again tomorrow.

**Comment by SnowShock35** [comment]
@johnnymobbins kk

**Comment by johnnymobbins** [comment]
Removed but will research further
