### ISSUE TITLE
bed explodes

### ISSUE THREAD

**Issue by Turmfalke2** [SnowShock35/Obscurity#99]
hi,
I just finished the Nap time! quest that rewards the player with a bed. It seemed reasonable to me to directly place and use the bed. Turns out this is a bad idea. Everything in my compact machine exploded, countless chests got destroyed. My only hope now is that nothing irrecoverable got destroyed.
Seriously, what is the idea behind this quest? Usually beds aren't made of tnt.

**Comment by AKTheKnight** [comment]
This is a feature of the mod, similar to the way beds explode in the end.

The mod is traditionally used as a compact machine, not for living in. That is why there are some aspects which are not perfect for our uses.

It might be worth checking whether you have a world backup you can use (they are taken on login, logout and every two hours)

**Comment by Turmfalke2** [comment]
How is that reasonable? Beds are commonly made of wool and on top of some planks, there is nothing that indicates that they will spontaneously explode when you attempt to lay in them. 
With the nether you can at least reason that it a hellish environment and sleeping there is not safe, however the compact machine are more like perfectly sterile and sheltered vault. 

What is the point of giving the player an uncraftable bed? I don't think anyone is going to build a bedroom in the deep dark. Maybe you could add a warning in the quest book that beds explode? I don't think the mod is common enough that the average player is going to know about this peculiar interaction.

I have decided against restoring from a backup, to much has happened since then and I hope to be able to rebuild.

**Comment by SnowShock35** [comment]
@Turmfalke2 We'll see about changing/fixing this for the next version. However, keep in mind that it was intended for you to sleep in the deepdark. After all, this is where you are supposed to be in the game. Sure there isn't anything wrong with using the cubes as safe havens but, you are still supposed to have some sort of base or protected structure in the deep dark.

**Comment by johnnymobbins** [comment]
@Turmfalke2 Thanks for the report, hope you didn't loose too much stuff!
I have re-written the quest to give a bit more of a hint. Hope you like the change :P

**Comment by Turmfalke2** [comment]
@SnowShock35: Oh I was under the impression that the defining feature of the modpack was that you live in the complex machine world. When ever I leave my "base" I just pick up the entrance block and carry my base with me. So I am living kind of like a nomad with a house trailer.

**Comment by AKTheKnight** [comment]
We aren't the ones who decided to have beds explode. That's the way the mod author wrote the mod

**Comment by SnowShock35** [comment]
@Turmfalke2 Sure, you can have a base in them which works well and is thinking outside the box but no the idea is that you have to survive in the deep dark mainly. And no this wont change. Sorry
